### ISSUE TITLE
it doesn't work 

### ISSUE THREAD

**Issue by tommyna5** [dolanmiu/MMM-awesome-alexa#1]
when I try to run the mirror it gives this error 
<img width="492" alt="screen shot 2017-05-05 at 9 08 16 pm" src="https://cloud.githubusercontent.com/assets/22130416/25758394/15ed2572-31d7-11e7-891e-4256381659b2.png">

**Comment by dolanmiu** [comment]
Run npm run build first

Thanks,

Let me know if that sorts it

I should probably mention that on the README

**Comment by dolanmiu** [comment]
I updated the README to reflect this

**Comment by tommyna5** [comment]
I got an error when I ran npm run build 
`> mmm-awesome-alexa@1.0.0 build /Users/tommy/Desktop/MagicMirror-master/modules/MMM-awesome-alexa
> rimraf dist && npm run webpack && npm run tsc

sh: rimraf: command not found

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mmm-awesome-alexa@1.0.0 build: `rimraf dist && npm run webpack && npm run tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 build script 'rimraf dist && npm run webpack && npm run tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mmm-awesome-alexa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf dist && npm run webpack && npm run tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mmm-awesome-alexa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mmm-awesome-alexa
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tommy/.npm/_logs/2017-05-05T18_28_27_656Z-debug.log
`
npm version 4.2.0

**Comment by tommyna5** [comment]
maybe because i'm using a mac ?

**Comment by dolanmiu** [comment]
Run 

Npm install

I am using a mac too 😊

**Comment by dolanmiu** [comment]
Updated README again to reflect this

**Comment by tommyna5** [comment]
sorry but I'm still getting errors even when I ran npm install 
```
**Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.**
 - configuration.output.path: The provided value "./dist" is not an absolute path!

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "webpack"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmm-awesome-alexa@1.0.0 webpack: `webpack --config config/webpack.main.js --progress --profile --bail --display-error-details`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 webpack script 'webpack --config config/webpack.main.js --progress --profile --bail --display-error-details'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mmm-awesome-alexa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config config/webpack.main.js --progress --profile --bail --display-error-details
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mmm-awesome-alexa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mmm-awesome-alexa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tommy/.npm/_logs/2017-05-05T19_19_07_788Z-debug.log

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmm-awesome-alexa@1.0.0 build: `rimraf dist && npm run webpack && npm run tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 build script 'rimraf dist && npm run webpack && npm run tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mmm-awesome-alexa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf dist && npm run webpack && npm run tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mmm-awesome-alexa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mmm-awesome-alexa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tommy/.npm/_logs/2017-05-05T19_19_07_840Z-debug.log
```

**Comment by dolanmiu** [comment]
I will need to look at this when I get home!

**Comment by dolanmiu** [comment]
I have updated webpack, it is because now webpack does not support relative path values:

https://github.com/webpack/webpack/issues/4549

Please try again and let me know!

**Comment by tommyna5** [comment]
I ran npm run build successfully but when i try to use the mirror i'm getting a blank screen and this erorr in terminal 
Recording with sample rate 16000...
Whoops! There was an uncaught exception...
```
{ Error: spawn rec ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn rec',
  path: 'rec',
  spawnargs: 
   [ '-q',
     '-r',
     16000,
     '-c',
     '1',
     '-e',
     'signed-integer',
     '-b',
     '16',
     '-t',
     'wav',
     '-',
     'silence',
     '1',
     '0.1',
     '0%',
     '1',
     '1.0',
     '0%' ] }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

```
I checked conifg.js and there is nothing wrong I don't why I keep getting errors 
sorry for the trouble

**Comment by dolanmiu** [comment]
So sorry, I forgot to put yet another step:

You need to install `sox`

For OS X (need homebrew):

```bash
$ brew install sox
```

For linux:

```bash
$ sudo apt-get install sox libsox-fmt-all
```

I will update the README

No! Don't be sorry, without you, I probably wouldn't have known these issues! Keep them coming! 😄

**Comment by bogdan1133** [comment]
I got the same error where it cant load the config file , and showing a blank screen without any widgets. I have followed all the steps, it shows that a specific file in snowboy in the module folder not found.

**Comment by dolanmiu** [comment]
try:

```sh
$ sudo npm install --unsafe-perm
```

This is from:

http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

Let me know how it goes!

**Comment by bogdan1133** [comment]
Thank you for replying. 

I got a big error in the module itself when running that command:
> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild

✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
make: Entering directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:128: recipe for target 'Release/obj.target/snowboy.node' failed
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
make: *** [Release/obj.target/snowboy.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "/usr/bin/nodejs" "/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.6" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.6-linux-arm" "--remote_path=./snowboy/v1.1.0/Release/" "--package_name=snowboy-v1.1.0-electron-v1.6-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 

Failed with exit code: 1

Error: make: Entering directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
snowboy.target.mk:128: recipe for target 'Release/obj.target/snowboy.node' failed
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
make: *** [Release/obj.target/snowboy.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "/usr/bin/nodejs" "/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/.bin/node-gyp" "rebuild" "--target=1.6.6" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v1.6-linux-arm" "--remote_path=./snowboy/v1.1.0/Release/" "--package_name=snowboy-v1.1.0-electron-v1.6-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/spawn-rx/lib/src/index.js:262:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:236:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:197:26)
    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:102:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/spawn-rx/lib/src/index.js:236:65)
    at SafeSubscriber.__tryOrSetError (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:245:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:187:27)
    at Subscriber._next (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:125:26)
    at Subscriber.next (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:89:18)
    at ReduceSubscriber._complete (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/operator/reduce.js:119:30)
    at ReduceSubscriber.Subscriber.complete (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:114:18)
    at MergeAllSubscriber._complete (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/operator/mergeAll.js:94:30)
    at MergeAllSubscriber.Subscriber.complete (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Subscriber.js:114:18)

Another error when tried to run that command in the node_modules/snowboy:
> snowboy@1.1.0 prepublish /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
> tsc --listFiles

error TS6053: File '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/SnowboyDetectNative.d.ts' not found.
error TS6053: File '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.ts' not found.
error TS6053: File '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/node-pre-gyp.d.ts' not found.
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/node_modules/typescript/lib/lib.es6.d.ts
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/node_modules/@types/node/index.d.ts
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/@types/form-data/index.d.ts
/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/@types/request/index.d.ts

**Comment by dolanmiu** [comment]
Could we talk on here, it will be quicker:

https://gitter.im/awesome-alexa/Lobby

I have not tried it on a Raspberry Pi 3 because my Rasperry Pi does not have a mic!
