### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by JohnB7777** [dolanmiu/MMM-awesome-alexa#10]
Hello,

I have a big problem : if I start the magic mirror, I have a black screen and I can do nothing...
I followed all the steps (including the one to have the refresh token) and I put the module config on config.js
Would anyone have a solution ?

Thank you !

**Comment by dolanmiu** [comment]
Can you do:

```
$ npm start dev
```

And tell me what errors you get in the console? That will allow me to help much more!

**Comment by JohnB7777** [comment]
I tried to solve this problem and now I have no more black screen ! :)
I have to wait until next week to receive my microphone to test the voice.
If Alexa is well installed, will it recognize all types of voice commands ?
Thank you ! :)

**Comment by dolanmiu** [comment]
Yes all commands, 

But it won't recognise conversational type commands which require you to talk back, for example:

You: "Set me a reminder for tomorrow"
Alexa: "Sure, for what time?"
... stops

There will be a fix soon once NodeJS has HTTP/2 support. Then there will be a rewrite of some sort!

**Comment by henrikra** [comment]
@JohnB7777 Is this fixed?

**Comment by dolanmiu** [comment]
Seems to be

The issue got a bit side tracked

Closing
