### ISSUE TITLE
where to find ((( Authorization code from previous step))) help please

### ISSUE THREAD

**Issue by yehia999** [dolanmiu/MMM-awesome-alexa#103]
where to find ((( Authorization code from previous step))) help please

If you know how to fix the issue, make a pull request instead.

**Comment by henrikra** [comment]
I guess he is reading old wikis https://github.com/dolanmiu/MMM-awesome-alexa/wiki

**Comment by dolanmiu** [comment]
Here is the updated wiki, I have deprecated the articles and pointed to correct direction:

https://github.com/dolanmiu/MMM-awesome-alexa/wiki/How-to-get-AVS-Token

**Comment by dolanmiu** [comment]
Closing due to no response.

Please reopen if there is still trouble
