### ISSUE TITLE
Refresh Token not working

### ISSUE THREAD

**Issue by g2bb** [dolanmiu/MMM-awesome-alexa#11]
After many struggles I was able to obtain the access and refresh tokens, however the module still does not work for me and I do not know why. My best guess is it has something to do with the refresh token because my script that is supposed to get me new refresh and access tokens returns this:
```
{"error_description":"The server encountered an internal error trying to fulfill the request","error":"ServerError"}
```

but my script is identical to what is on the tutorial:
```
REFRESH="Atza|IwEBIIFls2PotM,,,"
CLIENT_ID="amzn1.application-oa2-client.17c..."
CLIENT_SECRET="477e9e0a1ba4..."
GRANT_TYPE="refresh_token"
REDIRECT_URI="https://localhost:9745/authresponse"
curl -X POST --data "grant_type=${GRANT_TYPE}&refresh_token=${REFRESH}&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&redirect_uri=${REDIRECT_URI}" https://api.amazon.com/auth/o2/token 
```
"..." to shorten and protect any information

Additionally I continue to get the "Please create a config file" screen when booting MM despite having all the information there: 
```
{
  			module: 'MMM-awesome-alexa',
  			position: 'bottom_bar',
			config: {
			    	wakeWord: 'Alexa',
 			    	clientId: 'amzn1.application-...',
    			    	clientSecret: '477e9e0a1ba4015569b...',
				deviceId: 'MagicMirror',
			    	refreshToken: 'Atza|IwEBIIFls2PotMBiq3uSEpiX...',
}
```
"..." to shorten and protect any information

Despite my best efforts this has puzzled me off and on all day and I just can't seem to get it. Any help would be greatly appreciated. While I am no programer, I am certainly not a novice so technical details are welcomed. I have more documents like the Auth and Access scripts that I can send if that information is needed.

**Comment by dolanmiu** [comment]
Can you run your config file through:

http://esprima.org/demo/validate.html

When it says "Please create a config file", it normally means your config is syntactically wrong somehow

**Comment by g2bb** [comment]
I ran it through and I did find one issue that I corrected, but it is still not starting and if I comment out MMM-awesome-alexa it works perfectly

**Comment by dolanmiu** [comment]
As in, if you add MMM-awesome-alexa config, you get "Please create a config file"?

Are you running the mirror using `PM2` or `npm start`?

There is an issue with it not working with PM2, `npm start` works fine for me though

**Comment by dolanmiu** [comment]
Wait, I think I know whats wrong:

```
{
  			module: 'MMM-awesome-alexa',
  			position: 'bottom_bar',
			config: {
			    	wakeWord: 'Alexa',
 			    	clientId: 'amzn1.application-...',
    			    	clientSecret: '477e9e0a1ba4015569b...',
				deviceId: 'MagicMirror',
			    	refreshToken: 'Atza|IwEBIIFls2PotMBiq3uSEpiX...',
                       }
}
```

try that, I added an extra bracket which was missing.

I ammended the README to reflect this change.

**Comment by g2bb** [comment]
Welp, that worked briefly, however after a reboot I just get a black screen, my cursor doesn't disappear like it should and I can't minimise the screen to run a reboot so I have to do a hard reboot. No "Please create a config file" screen or anything. I do remember that there is an update for the Magic Mirror so I'll check that and let you know how it goes, however any insight into this issue would help.

**Comment by dolanmiu** [comment]
I'm guessing you are using PM2, this library has an issue with PM2, try `npm start dev`, and then show me the error

That will give way more insight

**Comment by g2bb** [comment]
This is the only error I got:
`WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module './dist/main/index.js'
`

This is what my startup script is now (the only difference between this and my default script is that I added "dev" to it):
`cd ~/MagicMirror 
DISPLAY=:0 npm start dev
$SHELL`

When I run that (with dev) the screen is white and a bar at the bottom shows up that looks like the Google Chrome Developer Tools and says "DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect."

**Comment by dolanmiu** [comment]
Seems so odd, paste your entire config here, but blank out the private stuff

**Comment by g2bb** [comment]
I will later tonight. I'm at the 4th of July weekend party

**Comment by g2bb** [comment]
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 */

var config = {
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],

	language: 'en',
	timeFormat: 12,
	units: 'imperial',

	modules: [
		/* {
			module: "updatenotification",
			position: "top_bar"
		}, */
		{
			module: 'clock',
			position: 'top_left'
		},
		{
			module: 'MMM-wordnik',
			position: 'bottom_left',
			config: {
				api_key: '7fd5868a62....'
			}
		},
		{
		        module: 'MMM-SimpleLogo',
        		position: 'bottom_right',    // This can be any of the regions.
        		config: {
        			// The config property is optional.
            			// See 'Configuration options' for more information.
				// fileUrl: 'img/---.png'
   			}
   		},
		{
  			module: 'MMM-awesome-alexa',
  			position: 'bottom_bar',
			config: {
			    	wakeWord: 'Alexa',
 			    	clientId: 'amzn1.application-oa2-client.17cc4553...',
    			    	clientSecret: '477e9e0a1ba4015569bbc4...',
				deviceId: 'MagicMirror',
			    	refreshToken: 'Atzr|IwEBIFHYU40TZnIsx9gYlRbesi0...',
                       }
		},
		{
			module: 'newsfeed',
			position: 'bottom_bar',
			config: {
				ignoreOldItems: true,
				ignoreOlderThan: 604800000,
				showSourceTitle: true,
				showPublishDate: true,
				feeds: [
				/*	{
						title: "RSSTechMix",
						url: "http://www.rssmix.com/u/8231889/rss.xml"
					},	*/
					{
						title: "Mobile Crunch",
						url: "http://feeds.feedburner.com/Mobilecrunch"
					},
					{
						title: "Crunch Gear",
						url: "http://feeds.feedburner.com/crunchgear"
					},
					{
						title: "TechCrunch Android",
						url: "http://feeds.feedburner.com/TechCrunch/Android"
					},
					{
						title: "TechCrunch Google",
						url: "http://feeds.feedburner.com/TechCrunch/Google"
					},
					{
						title: "TechCrunch Facebook",
						url: "http://feeds.feedburner.com/TechCrunch/Facebook"
					},
					{
						title: "TechCrunch Samsung",
						url: "http://feeds.feedburner.com/TechCrunch/Samsung"
					},
					{
						title: "TechCrunch Apple",
						url: "http://feeds.feedburner.com/TechCrunch/Apple"
					},
					{
						title: "TechCrunch iPhone",
						url: "http://feeds.feedburner.com/TechCrunch/iphone"
					},
					{
						title: "TechCrunch Amazon",
						url: "http://feeds.feedburner.com/TechCrunch/Amazon"
					},
					{
						title: "Wired",
						url: "http://feeds.cnevids.com/brand/wired.mrss"
					},
					{
						title: "Wired Security",
						url: "https://www.wired.com/category/security/feed/"
					},
					{
						title: "Wired Design",
						url: "https://www.wired.com/category/design/feed/"
					},
					{
						title: "Wired Gear",
						url: "https://www.wired.com/category/gear/feed/"
					},
					{
						title: "Wired Reviews",
						url: "https://www.wired.com/category/reviews/feed/"
					},
					{
						title: "Wired Science",
						url: "https://www.wired.com/category/science/feed/"
					},
					{
						title: "Wired Photo",
						url: "https://www.wired.com/category/photo/feed/"
					},
					{
						title: "Wired Business",
						url: "https://www.wired.com/category/business/feed/"
					},
					{
						title: "Wired Underwire",
						url: "https://www.wired.com/category/underwire/feed/"
					},
					{
						title: "Wired Transportation",
						url: "https://www.wired.com/category/transportation/feed/"
					},
					{
						title: "Wired Science Blogs",
						url: "https://www.wired.com/category/science/science-blogs/feed/"
					},
				/*	{
						title: "Title",
						url: "URL"
					},
					{
						title: "Title",
						url: "URL"
					},
					{
						title: "Title",
						url: "URL"
					},
					{
						title: "Title",
						url: "URL"
					},
					{
						title: "Title",
						url: "URL"
					},
					{
						title: "Title",
						url: "URL"
					}	*/
				],
			}
		},
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}

**Comment by dolanmiu** [comment]
It's because you are missing a closing brace in your config, the `]` is missing on line 170.

```js
		}],
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
```

**Comment by g2bb** [comment]
That is helpful, however I am still getting the black screen (Or white if I launch in DEV mode)

**Comment by dolanmiu** [comment]
If you click on the console in DEV mode, can you see any error, there is normally a reason for it

Paste the error here

**Comment by g2bb** [comment]
This is exactly what it outputs

`
> magicmirror@2.1.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.1.1
Loading config ...
Loading module helpers ...
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-wordnik
No helper found for module: MMM-SimpleLogo.
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module './dist/main/index.js'
Loading module helpers ...
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-wordnik
No helper found for module: MMM-SimpleLogo.
App threw an error during load
Error: Cannot find module './dist/main/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:3:14)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:43:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module './dist/main/index.js'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:3:14)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:43:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
`

**Comment by dolanmiu** [comment]
```
 Cannot find module './dist/main/index.js'
```
it means the module needs to be npm installed, and built

so go into the MMM-awesome-alexa folder, and run:

```
$ npm install
```

it should run `npm run build` automatically, but if not, run that.

**Comment by g2bb** [comment]
So the `npm install` did *not* run the `npm run build` so I did and here is what I got:
[https://pastebin.com/VmezXBzQ](url)
I put it in a paste bin because it is quite long and in depth and I didn't want the lines to merge

**Comment by dolanmiu** [comment]
Do a `git pull`, and run those commands again, I made an update which fixed that actually

`node` or `request` had a clash and it broke stuff

**Comment by g2bb** [comment]
I tried bot a git pull and a completely new git installation and neither worked. On both I got the same blank black screen.

**Comment by dolanmiu** [comment]
Totally new git folder, deleted `node_modules` and` package-lock.json`?

From TravisCI, I can tell that it definately works, its green:

https://travis-ci.org/dolanmiu/MMM-awesome-alexa

If that dont work, I will try tomorrow on my mac

**Comment by g2bb** [comment]
I'll try later tonight, I'm at a 4th oh July party right now, sorry

**Comment by dolanmiu** [comment]
ok no problem, have fun!

**Comment by g2bb** [comment]
To answer your question, what i did for the new git folder was rename (effectively remove) the old folder and cloned the git from the modules folder on the command prompt. So my guess would be no, I did not delete those things unless they were in that folder.

Also I am unsure what to do with the travis-ci.org link that you gave me. Sorry if I am missing something obvious

**Comment by dolanmiu** [comment]
Works for me fine:

```shell
Dolans-MacBook-Pro:MagicMirror dolan$ git clone https://github.com/dolanmiu/MMM-awesome-alexa.git
Cloning into 'MMM-awesome-alexa'...
remote: Counting objects: 1062, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 1062 (delta 13), reused 16 (delta 6), pack-reused 1038
Receiving objects: 100% (1062/1062), 2.43 MiB | 1.03 MiB/s, done.
Resolving deltas: 100% (633/633), done.
Dolans-MacBook-Pro:MagicMirror dolan$ cd MMM-awesome-alexa/
Dolans-MacBook-Pro:MMM-awesome-alexa dolan$ npm install
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

> snowboy@1.2.0 preinstall /Users/dolan/MagicMirror/MMM-awesome-alexa/node_modules/snowboy
> npm install node-pre-gyp

npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.6.36
added 111 packages in 2.774s
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> snowboy@1.2.0 install /Users/dolan/MagicMirror/MMM-awesome-alexa/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/Users/dolan/MagicMirror/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v48-darwin-x64/snowboy.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> fsevents@1.1.2 install /Users/dolan/MagicMirror/MMM-awesome-alexa/node_modules/fsevents
> node install

[fsevents] Success: "/Users/dolan/MagicMirror/MMM-awesome-alexa/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/dolan/MagicMirror/MMM-awesome-alexa/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> mmm-awesome-alexa@1.0.0 postinstall /Users/dolan/MagicMirror/MMM-awesome-alexa
> npm run build


> mmm-awesome-alexa@1.0.0 build /Users/dolan/MagicMirror/MMM-awesome-alexa
> rimraf dist && npm run webpack && npm run tsc


> mmm-awesome-alexa@1.0.0 webpack /Users/dolan/MagicMirror/MMM-awesome-alexa
> webpack --config config/webpack.main.js --progress --profile --bail --display-error-details

 10% building modules 0/1 modules 1 active ...M-awesome-alexa/src/renderer/index.ts
[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from /Users/dolan/MagicMirror/MMM-awesome-alexa/tsconfig.json.

1379ms building modules                                                            
3ms sealing 
0ms optimizing 
0ms basic module optimization 
1ms module optimization 
1ms advanced module optimization 
0ms basic chunk optimization 
0ms chunk optimization 
0ms advanced chunk optimization 
1ms module and chunk tree optimization 
0ms chunk modules optimization 
0ms advanced chunk modules optimization 
1ms module reviving 
1ms module order optimization 
1ms module id optimization 
0ms chunk reviving 
1ms chunk order optimization 
2ms chunk id optimization 
3ms hashing 
0ms module assets processing 
8ms chunk assets processing 
1ms additional chunk assets processing 
0ms recording 
0ms additional asset processing 
0ms chunk asset optimization 
 94% asset optimization
[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.506 sec.
508ms asset optimization
7ms emitting 
Hash: 0e21208fa2637346ec8d
Version: webpack 3.0.0
Time: 1960ms
    Asset     Size  Chunks             Chunk Names
bundle.js  7.25 kB       0  [emitted]  bundle
   [0] ./src/renderer/index.ts 324 bytes {0} [built]
        factory:24ms building:1179ms = 1203ms
   [1] ./src/renderer/alexa-mirror.ts 1.46 kB {0} [built]
       [] -> factory:36ms building:89ms = 125ms
   [2] ./src/renderer/visualizer/rainbow-visualizer.ts 1.44 kB {0} [built]
       [] -> factory:39ms building:127ms = 166ms
   [3] ./src/renderer/visualizer/visualizer.ts 1.29 kB {0} [built]
       [] -> factory:6ms building:27ms = 33ms

> mmm-awesome-alexa@1.0.0 tsc /Users/dolan/MagicMirror/MMM-awesome-alexa
> tsc -p .

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN mmm-awesome-alexa@1.0.0 No repository field.

added 617 packages in 27.694s
```

**Comment by g2bb** [comment]
I just did the exact same commands and I got this. I don't know if it matters, but I am running this on a Raspberry Pi 3
[https://pastebin.com/XqiG61zi](url)

**Comment by dolanmiu** [comment]
Line 192 shows that the command is being run. Are you sure you don't have a `/dist` folder?

```
> tsc -p .
```

**Comment by g2bb** [comment]
I did a little looking around and I couldn't find one, but I don't really even know where to look. Where would it be if I have one?

**Comment by g2bb** [comment]
Oah, and what should I do with it if it turns out that I DO have one

**Comment by dolanmiu** [comment]
if you do, it means MagicMirror should find `MMM-awesome-alexa/dist/index.js`, and this module should work :)

**Comment by g2bb** [comment]
I found the dist folder and it has "main" and "render" folders as well as "bundle.js" but no "index.js"

**Comment by dolanmiu** [comment]
You shouldn't need to rename it to `index.js`, it should build and just work

Its no use pasting the bundle.js to me as I don't know what the build output is like!

Does the `/dist` folder also have `/main` and `/renderer` folders inside?

**Comment by g2bb** [comment]
The dist folder does include `/main` and `/render`

When I run `rec t.wav` I get this: `rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory`

**Comment by henrikra** [comment]
Looks like this can be closed 👍

**Comment by dolanmiu** [comment]
Closing

Thanks

**Comment by Bala0804** [comment]
I am trying the same steps as @dolanmiu mentioned. When I try to install the cloned package using NPM install, It is trying to download the snowboy from this link, and fails
[https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v59-linux-arm.tar.gz]

root@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa# npm install

> snowboy@1.2.0 preinstall /root/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
> npm install node-pre-gyp

npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.6.39
added 114 packages from 77 contributors and audited 266 packages in 30.736s
found 8 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> snowboy@1.2.0 install /root/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v59-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@9.11.2 (node-v59 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/root/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
In file included from ../../nan/nan.h:192:0,
                 from ../swig/Node/snowboy.cc:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:73: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
                                                                         ^
In file included from /root/.node-gyp/9.11.2/include/node/v8.h:26:0,
                 from /root/.node-gyp/9.11.2/include/node/node.h:63,
                 from ../../nan/nan.h:49,
                 from ../swig/Node/snowboy.cc:1:
/root/.node-gyp/9.11.2/include/node/v8.h:3165:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/root/.node-gyp/9.11.2/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
  COPY Release/snowboy.node
  COPY /root/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v59-linux-arm/snowboy.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/root/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

added 963 packages from 542 contributors and audited 12220 packages in 278.452s
found 593 vulnerabilities (540 low, 45 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by dolanmiu** [comment]
node 9 not supported, can you try node 8?
