### ISSUE TITLE
Localhost issue....

### ISSUE THREAD

**Issue by JiJoker1991** [dolanmiu/MMM-awesome-alexa#111]
Cant get the Token from AMAZON.

I USED always  https://localhost:3000/authresponse   for ALLOWED RETURN URL's

STEP: Configuring the Module 
1.npm run avs-token-helper
2.Follow the on screen instructions and give the script info it needs.
3.When I Copy/Paste the Generated Link from Terminal
4.The Site from Amazon open's up and asking for Login and AGREE
5.After AGREE, Site can't load, no connection to Localhost.....

What did I do:
Searching and reading 300 site's on Google and 2 hours on Youtube "Cats playing Keyboard"
#Create a SSH File in Root of PI...
#SETTINGS chrome://flags/ "allow Localhost"
#Blacklist IPV6 // disable ipv6 on "etc/modprobe.d/IPV6.config" 
#ADD 100 different "ALLOWED RETURN URL" for testing.............
#Make a new Security Profile on Amazon....
#Download a new Web Browser "Mozilla FireFox"

I don't Know what to do next....... :( 
PLEASE HELP ME !!!

here's the cat video https://www.youtube.com/watch?v=Kiklso4XJRw

**Comment by JiJoker1991** [comment]
Yes, My Allowed return URLs = https://localhost:3000/authresponse on Developer-Amazon


![1 von 4](https://user-images.githubusercontent.com/40057066/41200677-08da439e-6c99-11e8-8431-4cce5cd18d51.png)

--------------------------------------------------------------------------------------------------------------------------

![2 von 4](https://user-images.githubusercontent.com/40057066/41200679-0ebb0460-6c99-11e8-9be9-30e2678f04b5.png)

--------------------------------------------------------------------------------------------------------------------------

![3 von 4](https://user-images.githubusercontent.com/40057066/41200683-13f0da90-6c99-11e8-8e13-702484f936d4.png)

--------------------------------------------------------------------------------------------------------------------------

![4 von 4](https://user-images.githubusercontent.com/40057066/41200686-17d246e4-6c99-11e8-9cd5-5a5a2a4d6339.png)

**Comment by dolanmiu** [comment]
Oh that is normal, you have done everything correctly

The info you need is all in the address bar!

You need the code= part

Congrats

**Comment by JiJoker1991** [comment]
Thank you for the Answer, maybe I'm to stupid for this Part :D, sorry.
I try 
       # https://localhost:3000/authresponse?code=XXXXXXxxxxxXXXXxxxxXXXXXxxx=alexa%3Aall
I try 
       #                                                           code=XXXXXXxxxxxXXXXxxxxXXXXXxxx=alexa%3Aall
I try
       #                                                                  =XXXXXXxxxxxXXXXxxxxXXXXXxxx=alexa%3Aall
I try
       #                                                                    XXXXXXxxxxxXXXXxxxxXXXXXxxx=alexa%3Aall


![6 von 4](https://user-images.githubusercontent.com/40057066/41440927-f77251d4-701f-11e8-8547-e83ae0237c5a.png)

----------------------------------------------------------------------------------------------------------------------------

![5 von 4](https://user-images.githubusercontent.com/40057066/41440733-4f3a3ea0-701f-11e8-9327-8603abc1dd8b.png)

**Comment by dolanmiu** [comment]
They are all wrong, only do:

XXXXXXxxxxxXXXXxxxxXXXXXxxx

Without the http://localhost:3000/authresponse, without the Alexa part

Only do the xxx

**Comment by JiJoker1991** [comment]
Thank you very much,
Now it works :) :+1: , 

"BUT"

I copy the Module in my config.js and take my Client ID / Client Secret/ refresh token and and and...
When I start the MagicMirror, there is a Warning!  "SNOWBOY" , then it starts only default Mode.

![config file](https://user-images.githubusercontent.com/40057066/41497160-76aefb26-713f-11e8-8e5e-ca08d72f9d03.png)

------------------------------------------------------------------------------------------------------------------------

![2018-06-16-082711_1824x984_scrot](https://user-images.githubusercontent.com/40057066/41497165-82a5abd2-713f-11e8-8460-c115572e14d2.png)



"BLACK MIRROR" no Modules, Can't Quit Mirror, only CTRL+ALT+DEL

I tried to delete Snowboy, try again
Downlaod Snowboy from your Site, try again


> magicmirror@2.3.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.3.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.

WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'snowboy'

Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
App threw an error during load
Error: Cannot find module 'snowboy'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:1382)
    at r (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:279)
    at Object.module.exports.Object.defineProperty.value (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:5363)
    at r (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:279)
    at Object.module.exports.Object.defineProperty.value (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:5735)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'snowboy'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:1382)
    at r (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:279)
    at Object.module.exports.Object.defineProperty.value (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:5363)
    at r (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:279)
    at Object.module.exports.Object.defineProperty.value (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:5735) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: updatenotification
Stopping module helper: calendar

![new issue](https://user-images.githubusercontent.com/40057066/41497043-b59bbdb8-713c-11e8-92c7-7ed6382dc527.png)

When I delete the "Module" from Config.js, Mirror works normal.

**Comment by dolanmiu** [comment]
Congrats!

Have you ran npm install?

If you have, delete the the modules node_modules, and run it again

**Comment by JiJoker1991** [comment]
NOW IT WORKS :+1: 

I found more Problems.
For Everbody with the same Problems ;-)
PROBLEM 1:

On install pyaudio: ERROR $ pip install pyaudio
![error1 1 von 3](https://user-images.githubusercontent.com/40057066/41542788-111214a0-7316-11e8-8e05-9b1f17ee426e.png)
-----------------------------------------------------------------------------------
![error1 2 von 3](https://user-images.githubusercontent.com/40057066/41542809-1a70ab38-7316-11e8-86a9-0d29f2c28cf5.png)
-----------------------------------------------------------------------------------
![error1 3 von 3](https://user-images.githubusercontent.com/40057066/41542829-2190d50a-7316-11e8-9977-6b48046fa6f2.png)
-----------------------------------------------------------------------------------

SOLUTION for ERROR 1:

sudo apt update && sudo apt upgrade

sudo apt-get install libportaudio2

sudo apt install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg libav-tools

and again  //                   pip install pyaudio

PROBLEM 2:

On install ERROR $ npm install --only=prod

![error 2 1 von 2](https://user-images.githubusercontent.com/40057066/41543045-6efdbbfa-7316-11e8-9e93-b609fc5bf60e.png)
-------------------------------------------------------------------------
![error 2 2 von 2](https://user-images.githubusercontent.com/40057066/41543063-7e65fc7e-7316-11e8-8436-a01ebdfe47ee.png)

SOLUTION for ERROR 2:

1.            cd ~/MagicMirror/modules # navigate to module folder
2.            cd MMM-awesome-alexa # go into the module directory

It should look like this --> pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ 

Then: remove the node install

3.            curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
4.            sudo apt-get install -y nodejs

And then running the installer again

5.            npm install --only=prod
6.            npm run electron-rebuild

Hope it works  :+1:

**Comment by Jacob12138xieyuan** [comment]
I only copied the code between = and &, but I still got ‘the request has a invalid grand parameter: code’. Can you help me?

**Comment by mrprincehd** [comment]
`npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg== integrity checksum failed when using sha512: wanted sha512-L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg== but got sha1-NgSLv/TntH4TZkQxbJlmnqWukfE=. (2872 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm notice save electron-rebuild is being moved from dependencies to devDependencies
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})`

**Comment by dolanmiu** [comment]
The localhost issue is expected, it is part of the install procedure

I have re-written the tool to make it easier to use:

https://awesome-alexa.js.org/#/installation?id=configuration

**Comment by alexbjjsoul** [comment]
hi i cant install 

npm install --only = prod

help
i have the same error

**Comment by joelafonso** [comment]
> On install ERROR $ npm install --only=prod


I am having the same issue and your solution for error 2 didnt work unfortunately... :'(
