### ISSUE TITLE
wakeWord setting not working

### ISSUE THREAD

**Issue by flyingchipmunk** [dolanmiu/MMM-awesome-alexa#113]
The wakeWord config option appears to not work, it always reverts to 'Alexa'

```
            module: "MMM-awesome-alexa",
            position: "bottom_bar",
            config: {
                wakeWord: "MagicMirror",
            ...
```
pm2 log MagicMirror points to a root cause perhaps:

`0|MagicMir | model MagicMirror is not found, so using Alexa instead`

**Comment by flyingchipmunk** [comment]
Ah a little code inspection and I found the hard coded only supported model names in model-dictionary.ts

closing issue.

**Comment by dolanmiu** [comment]
Thanks 👍
