### ISSUE TITLE
No more modules!

### ISSUE THREAD

**Issue by OzzyPsycko** [dolanmiu/MMM-awesome-alexa#115]
Hi,

First of all thank you!
I have been struggling with the refresh token but that is sorted now.
The issue I have seems to be with electron.
So I did all of that:

$ cd ~/MagicMirror/modules # navigate to module folder
$ git clone https://github.com/dolanmiu/MMM-awesome-alexa.git # clone this repository
$ cd MMM-awesome-alexa # go into the module directory
$ npm install --only=prod

no problem there
where it got funny is with this:

$ npm run electron-rebuild

Throwing errors everytime I was trying to run it. So I looked in all the Issues people kindly raised and I found someone saying it should look like this:

$ npm run --electron-rebuild

Which I did and I got the following result:
<pre><font color="#729FCF"><b>~/MagicMirror/modules/MMM-awesome-alexa</b></font>$ npm run --electron-rebuild
Lifecycle scripts included in mmm-awesome-alexa:
  test
    npm run lint

available via `npm run-script`:
  build
    webpack --progress --profile --bail --display-error-details
  dev
    npm run build -- --watch --mode development
  electron-rebuild
    electron-rebuild --pre-gyp-fix
  lint
    tslint --project .
  node-pre-gyp
    node-pre-gyp clean configure build
  test-rec
    bash test-rec.sh
  spell
    cspell src/**/*.ts
  style
    prettier -l src/**/*.ts
  avs-token-helper
    node avs-helper/avs-token-helper.js
  avs-refreshToken-helper
    node avs-helper/avs-refreshToken-helper.js
  build.avs-helper
    tsc --p tsconfig.avs-helper.json
</pre>
So I assumed that it worked (?)
But then I setup the config file with my token and launch the mirror but all I get is a black screen! Apparently it cannot find the snowboy.node in the electron folder.
I search the Issues messages again and it is suggested to  delete the nodes_modules folder in MMM-awesome-alexa and run the npm install again, which I did, followed by the --electron-rebuild.
But all I got is a black screen!
Below is what the terminal is telling me, I hope you will be able to help me!
<pre><font color="#729FCF"><b>~/MagicMirror</b></font>$ npm start dev

&gt; magicmirror@2.4.0 start /home/ozzypsycko/MagicMirror
&gt; sh run-start.sh &quot;dev&quot;

Starting MagicMirror: v2.4.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-MyCalendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: newsfeed
<font color="#CC0000">WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module &apos;/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-x64/snowboy.node&apos;</font>
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-MyCalendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: newsfeed
App threw an error during load
Error: Cannot find module &apos;/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-x64/snowboy.node&apos;
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/ozzypsycko/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.&lt;anonymous&gt; (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.&lt;anonymous&gt; (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:132:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module &apos;/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-x64/snowboy.node&apos;
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/ozzypsycko/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.&lt;anonymous&gt; (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.&lt;anonymous&gt; (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/index.js:132:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: &apos;MODULE_NOT_FOUND&apos; }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
^CShutting down server...
Stopping module helper: updatenotification
Stopping module helper: MMM-MyCalendar
Stopping module helper: newsfeed
Stopping module helper: updatenotification
Stopping module helper: MMM-MyCalendar
Stopping module helper: newsfeed
</pre>

**Comment by OzzyPsycko** [comment]
Forgot to add the error messages from npm run electron-rebuild:
<pre><font color="#729FCF"><b>~/MagicMirror/modules/MMM-awesome-alexa</b></font>$ npm run electron-rebuild

&gt; mmm-awesome-alexa@1.0.0 electron-rebuild /home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa
&gt; electron-rebuild --pre-gyp-fix

<font color="#06989A">⠋</font> Searching dependency tree<font color="#CC0000">An unhandled error occurred inside electron-rebuild</font>
<font color="#CC0000">Could not detect abi for version 2.0.0 and runtime electron.  Updating &quot;node-abi&quot; might help solve this issue if it is a new release of electron</font>

<font color="#CC0000">Error: Could not detect abi for version 2.0.0 and runtime electron.  Updating &quot;node-abi&quot; might help solve this issue if it is a new release of electron</font>
<font color="#CC0000">    at Object.getAbi (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-abi/index.js:44:9)</font>
<font color="#CC0000">    at new Rebuilder (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/rebuild.js:43:28)</font>
<font color="#CC0000">    at Object.rebuild (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/rebuild.js:217:23)</font>
<font color="#CC0000">    at Object.&lt;anonymous&gt; (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/cli.js:100:33)</font>
<font color="#CC0000">    at Generator.next (&lt;anonymous&gt;)</font>
<font color="#CC0000">    at fulfilled (/home/ozzypsycko/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/cli.js:5:58)</font>
<font color="#CC0000">    at &lt;anonymous&gt;</font>
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> 255
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Exit status 255
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

</pre>

**Comment by denverquane** [comment]
So the comment you/I saw elsewhere saying to run with the `--electron-rebuild` argument is not correct, you have to use the original `electron-rebuild` command in order for it to even try the install.

What worked for me to actually fix the original error was to update my npm installation using `npm install npm@latest -g`, and then install the "node-abi" package, by doing `npm install node-abi` from within the MM-awesome-alexa directory.

Let me know if that works, I had the same error and (I think) those are the two steps that fixed the issue for me.

Good luck!

**Comment by OzzyPsycko** [comment]
@denverquane 
First of, thank you for your reply!
Second, THANK YOU I just did what you suggested and it now works!
