### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Scarala** [dolanmiu/MMM-awesome-alexa#116]
Trying to install on a RasPi 1. all manual installation-steps successful but when i get to the last step
`npm run electron-rebuild`
i get this error

> Error: Cannot find module 'rxjs/add/observable/of'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/spawn-rx/lib/src/index.js:16:1)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> 
> npm ERR! Linux 4.14.52+
> npm ERR! argv "/opt/node-v10.6.0-linux-armv6l/bin/node" "/usr/bin/npm" "run" "electron-rebuild"
> npm ERR! node v10.6.0
> npm ERR! npm  v2.15.12
> npm ERR! code ELIFECYCLE
> npm ERR! mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script 'electron-rebuild --pre-gyp-fix'.
> npm ERR! This is most likely a problem with the mmm-awesome-alexa package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     electron-rebuild --pre-gyp-fix
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mmm-awesome-alexa
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls mmm-awesome-alexa
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/pi/MagicMirror/modules/MMM-awesome-alexa/npm-debug.log

The log-file includes

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/opt/node-v10.6.0-linux-armv6l/bin/node',
> 1 verbose cli   '/usr/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'electron-rebuild' ]
> 2 info using npm@2.15.12
> 3 info using node@v10.6.0
> 4 verbose run-script [ 'preelectron-rebuild',
> 4 verbose run-script   'electron-rebuild',
> 4 verbose run-script   'postelectron-rebuild' ]
> 5 info preelectron-rebuild mmm-awesome-alexa@1.0.0
> 6 info electron-rebuild mmm-awesome-alexa@1.0.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info mmm-awesome-alexa@1.0.0 Failed to exec electron-rebuild script
> 9 verbose stack Error: mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (/opt/node-v10.6.0-linux-armv6l/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
> 9 verbose stack     at EventEmitter.emit (events.js:182:13)
> 9 verbose stack     at ChildProcess.<anonymous> (/opt/node-v10.6.0-linux-armv6l/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 9 verbose stack     at ChildProcess.emit (events.js:182:13)
> 9 verbose stack     at maybeClose (internal/child_process.js:961:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
> 10 verbose pkgid mmm-awesome-alexa@1.0.0
> 11 verbose cwd /home/pi/MagicMirror/modules/MMM-awesome-alexa
> 12 error Linux 4.14.52+
> 13 error argv "/opt/node-v10.6.0-linux-armv6l/bin/node" "/usr/bin/npm" "run" "electron-rebuild"
> 14 error node v10.6.0
> 15 error npm  v2.15.12
> 16 error code ELIFECYCLE
> 17 error mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
> 17 error Exit status 1
> 18 error Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script 'electron-rebuild --pre-gyp-fix'.
> 18 error This is most likely a problem with the mmm-awesome-alexa package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     electron-rebuild --pre-gyp-fix
> 18 error You can get information on how to open an issue for this project with:
> 18 error     npm bugs mmm-awesome-alexa
> 18 error Or if that isn't available, you can get their info via:
> 18 error
> 18 error     npm owner ls mmm-awesome-alexa
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

If i try to run Magic Mirror with `node serveronly dev` (Because of RasPi1) i get

> Starting MagicMirror: v2.4.1
> Loading config ...
> Loading module helpers ...
> No helper found for module: alert.
> Initializing new module helper ...
> Module helper loaded: updatenotification
> No helper found for module: clock.
> Initializing new module helper ...
> Module helper loaded: calendar
> No helper found for module: compliments.
> No helper found for module: currentweather.
> No helper found for module: weatherforecast.
> Initializing new module helper ...
> Module helper loaded: newsfeed
> WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module './util/root'
> Loading module helpers ...
> No helper found for module: alert.
> Initializing new module helper ...
> Module helper loaded: updatenotification
> No helper found for module: clock.
> Initializing new module helper ...
> Module helper loaded: calendar
> No helper found for module: compliments.
> No helper found for module: currentweather.
> No helper found for module: weatherforecast.
> Initializing new module helper ...
> Module helper loaded: newsfeed
> Whoops! There was an uncaught exception...
> { Error: Cannot find module './util/root'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/rxjs/Observable.js:2:14)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
> MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
> If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

Can anyone help?

**Comment by Scarala** [comment]
Just seen that i have installed node10.6 but npm 2.15.12
Trying to update npm and test it again

**Comment by dolanmiu** [comment]
Try and use node 8, node 10 tends to have issues

**Comment by Scarala** [comment]
i installed it on my raspi 2 now. everything works fine with node 6 installed
