### ISSUE TITLE
can i control my smart home devices with this module?

### ISSUE THREAD

**Issue by onkararj** [dolanmiu/MMM-awesome-alexa#120]
can i controll my  smart home devices with this module?

if yes.. then how can i do it?
if no. then is there any possibilities to do it?

**Comment by dolanmiu** [comment]
I think you can

I have not tried it, but you link your Alexa to:

https://alexa.amazon.co.uk/spa/index.html

Then it has a tab called "Smart Home"

**Comment by tylertech234** [comment]
https://alexa.amazon.com/spa/index.html
In the US. Thanks!!
