### ISSUE TITLE
Error during pip install pyaudio

### ISSUE THREAD

**Issue by lodesmets** [dolanmiu/MMM-awesome-alexa#122]
Hello when i try running pip install pyaudio I git this error:
  src/_portaudiomodule.c:29:23: fatal error: portaudio.h: Bestand of map bestaat niet
   #include "portaudio.h"
                         ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

Any idea?

**Comment by dolanmiu** [comment]
Is it something to do with this?

https://stackoverflow.com/questions/20023131/cannot-install-pyaudio-gcc-error

This is off-topic for this library, so I will close it soon

**Comment by lodesmets** [comment]
Fixed: I had to do this: sudo apt-get install portaudio19-dev.
Thanks for the quick response

**Comment by KC2016** [comment]
This is not working for me. Using Ubuntu 18.04.
src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory
     #include "portaudio.h"
              ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by KC2016** [comment]
I fixed it making an update with sudo.
