### ISSUE TITLE
Unmagle code

### ISSUE THREAD

**Issue by hundredrabh** [dolanmiu/MMM-awesome-alexa#123]
Hi,

I was wondering can the code be mode more readable?
Especially for MMM-awesome-alexa.js and node_helper.js.
Right  now code for both these files is in a single line.

I want to reuse parts of the code to see if I can enable Google Assistant too.

Thanks,
~Saurabh

**Comment by dolanmiu** [comment]
They are deliberately designed to be like that

They are intentionally not readable because it is compiled from TypeScript

look into the `src` folder, it is very readable
