### ISSUE TITLE
config/config.js

### ISSUE THREAD

**Issue by viksakshum** [dolanmiu/MMM-awesome-alexa#124]
If you know how to fix the issue, make a pull request instead.

* [ ] Before submitting your issue add logs from your MagicMirror by running command `pm2 log MagicMirror`

i am using raspberry pi 3 to setup this. done all the steps but in the end it says update your config/config.js  where is that? i dont see it in mmm-awesome-alexa module

**Comment by dolanmiu** [comment]
config/config.js is the MagicMirror one

MagicMirror/config/config.js

**Comment by viksakshum** [comment]
oops yes.. few questions on alexa configuration:

1. does it have to configured for "alexa for standalone app" or "Alexa enabled device" ?
2. for running avs helper i provide redirect url as http://google.com just to fulfil. this gives me a code. is that the one to use in the next step in config.js ?
3. i did a bluetooth speaker pairing with raspberry pi. now i can hear the sound. what option i can use for the mic ? its a raspberry pi 3 B+ ?
4. for testing can i type as well somehow until my point 3 is resolved.

kindly advise...

**Comment by viksakshum** [comment]
any help on this plz?

**Comment by dolanmiu** [comment]
1. Alexa enabled device
    ![image](https://user-images.githubusercontent.com/2917613/44551834-426c8380-a720-11e8-91f3-0d11974b3697.png)
2. yes it is
3. check out this guide: https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/docs/AudioSetup.md
4. no typing, sorry!

**Comment by viksakshum** [comment]
for point 3. yes i saw that, my question was more of what hardware do i need. i went ahead and ordered https://www.amazon.com/gp/product/B06XVMP7FF/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

does this look ok?

**Comment by dolanmiu** [comment]
Yup, that is the exact same one I've got

**Comment by viksakshum** [comment]
i got the mic today and it works fine as it can record. however, i am into a different issue now.  i am using a bluetooth speaker for audio. 

To get mic working i changed the settings exactky as you mentioned above in as ~/.asoundrc and it starts working. but then the bluetooth speaker does not work any more. also what i have seen is that if i disconnet/reconnect the bluetooth speaker the settings in my .asoundrc gets wiped and come back to original they had with mic broken,


Another question: i can see when i speak to alexa it is listening and then the dot animates to show that it is responding back as well. I thought it displays the text on the screen as well. I dont see that. What i am missing?

**Comment by viksakshum** [comment]
plz advise on this one

**Comment by dolanmiu** [comment]
The speaker I have no idea, its out of the scope of this module

I use the simple headphone port on my setup

Nope, it does not display text at all, the text in the video in the homepage u see is just "subtitles", it does not resemble the actual module

**Comment by viksakshum** [comment]
ok any ideas how to see the text ?

**Comment by viksakshum** [comment]
so i moved off from bluetooth speaker for now and using the audio jack for the audio. i can hear audio very well when i try opening youtube in browser. but with magic mirror i cannot hear the alexa response in my headphones.

what i am missing ?how to debug

**Comment by dolanmiu** [comment]
Is the Alexa circle animating? When you say `Alexa`, a circle should appear

what does it say when you start MagicMirror with `npm start dev`? Show me the logs

It should say "Listening", "Busy", "Idle", which means its working, if not then it is another issue

**Comment by viksakshum** [comment]
yes it animates . in fact i am sure it is working as my alexa app on mobile shows the correct card. 

but the issue is with the sound. i can hear sound on youtube via browser in raspberry pi but does not when alexa speaks back,

**Comment by dolanmiu** [comment]
Can you check if in the `modules/MMM-awesome-alexa/temp` folder has any sound files?

There should be one with your voice, and one with Alexa's voice. If they're there, then I have no idea, it should work.

If it is **not** there, then this is a bug

**Comment by dolanmiu** [comment]
Sound is out of scope of this module

Closing
