### ISSUE TITLE
another problem

### ISSUE THREAD

**Issue by fischi87** [dolanmiu/MMM-awesome-alexa#125]
hello, i started trying to install this module but i get this error:

`'The request has an invalid grant parameter : code',
  error: 'invalid_grant' }`

whats wrong here?

greedings

**Comment by dolanmiu** [comment]
Can you outline your steps?

**Comment by fischi87** [comment]
What u mean?
I did it like the readme. 
Is there a Problem with the redict url maybe? I wrote just my Website Domain Or what i have to Write there?

**Comment by dolanmiu** [comment]
you only need the XXXXXXX part, that is the code

Which step are you failing at?

**Comment by fischi87** [comment]
I Start the avs helper and write down the Auth code Then my Client id then my Secret key and them my redict url and After Return enter i get this error in my console.

**Comment by dolanmiu** [comment]
Are you sure your mic works? 

In the terminal type:

```
rec t.wav
```

**Comment by fischi87** [comment]
Thanks dir reply.

Yes it Record a file wehre i can Herr me.
It is Right that in my devices the Mirror are offline?

**Comment by dolanmiu** [comment]
> It is Right that in my devices the Mirror are offline?

Yes, they're offline on mine too. It would make sense that they're offline because this MMM plugin only sends requests back and forth to alexa, it never maintains an active connection

**Comment by fischi87** [comment]
Is there a way to Check If the Module is listen on the wakeword? I cant find a mistake.

**Comment by dolanmiu** [comment]
run:

```
npm start dev
```

to start MagicMirror in dev mode, you should see logs appear on the side when a wake word is heard

**Comment by mrprincehd** [comment]
Dear fischi87,
how were you able to solve this problem?

Thank you!

**Comment by dolanmiu** [comment]
I have re-written the token helper tool to be more user friendly and should be easier to follow:

https://awesome-alexa.js.org/#/installation?id=configuration

It seems you have resolved it, so im closing

Thanks!
