### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Oreo73** [dolanmiu/MMM-awesome-alexa#13]
Hello, I am fairly new to coding need help with this error everything else worked flawlessly Thank you

```
pi@rpi3z:~/MagicMirror/modules/MMM-awesome-alexa $ npm install
npm ERR! Linux 4.4.34-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! file /home/pi/.npm/path-parse/1.0.5/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/pi/.npm/path-parse/1.0.5/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/modules/MMM-awesome-alexa/npm-debug.log
```

**Comment by dolanmiu** [comment]
Can you try this?

https://stackoverflow.com/questions/31454607/npm-failed-to-parse-json

**Comment by Oreo73** [comment]
Heyy thank you for responding so fast. 
npm cache clean 
did the trick. Thank you again.
but now everything is done and I am currently stuck on the amazon auth code error page, they are saying that, they are working on it. Is it something I did wrong I followed it thoroughly, hung up on the last part for getting refresh token.

**Comment by dolanmiu** [comment]
Follow this guide to get a refresh token:

https://github.com/dolanmiu/MMM-awesome-alexa/wiki/How-to-get-AVS-Token

**Comment by Oreo73** [comment]
hello, I have the access token but not the refresh token. Could you help me retrieve it for Raspberry Pi

**Comment by dolanmiu** [comment]
Try the original guide, maybe you will get some more luck with that:

https://miguelmota.com/blog/alexa-voice-service-authentication/

**Comment by henrikra** [comment]
Looks like it is closing time for this 🎉
