### ISSUE TITLE
Compatible camera and Mic

### ISSUE THREAD

**Issue by mrprincehd** [dolanmiu/MMM-awesome-alexa#130]
Here is the error I am getting upon running the line
`npm install --only=prod`

```
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.6.39
added 114 packages in 114.632s

> snowboy@1.2.0 install /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v59-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@9.11.2 (node-v59 ABI, glibc) (falling back to source compile with node-gyp) 
```
I apologize if this such an easy problem to solve, I am relatively new to this and I would be deeply greatful for your help!

UPDATE: This got solved already. Nevermind.
---------------------------------------------------------------------------------------------------------------------------------

I am having trouble with a camera I just bought because the camera seems to be working fine but the microphone that comes with it seem to be not working with my RPi3 B and thus, my project smart mirror. Any recommendations on what camera and mic I should use? thanks

**Comment by dolanmiu** [comment]
Mic like this is what I use, seems to be good:

https://www.amazon.co.uk/Hosaire-Mini-Microphone-Laptop-Desktop/dp/B01IN197B0/ref=sr_1_19?ie=UTF8&qid=1536082587&sr=8-19&keywords=microphone+raspberry+pi

Camera, no idea. My RP3 barely manages to run MagicMirror, let alone camera software on top.

**Comment by mrprincehd** [comment]
Completely unrelated but I cant seem to find the log when i run npm start dev, ive read somewhere that it might be because of using python3/3.5 which I currently have?

**Comment by dolanmiu** [comment]
Solved. Closing

> Completely unrelated but I cant seem to find the log when i run npm start dev/ pm2 log... , ive read somewhere that it might be because of using python3/3.5 which I currently have?

No idea bro
