### ISSUE TITLE
Logitech C170 Setup on Smart Mirror  with Awesome Alexa Integration

### ISSUE THREAD

**Issue by mrprincehd** [dolanmiu/MMM-awesome-alexa#131]
So I am already in the process of adding up a webcam with a microphone for my smart mirror + alexa project. I am not really sure how to start the "setup phase" of my webcam. I only want the USB webcam to be my mic input (camera input for future projects) and the speakers would be my sound output.  Upon researching online, I came across FSWEBCAM, I dont think this will help me with the integration. 

So far, I think the mic is not working as Alexa is not responding to my wakeword (no animations whatsoever; I dont know where to find the logs in dev mode but i think it's not showing) . Thank you

**Comment by dolanmiu** [comment]
> So far, I think the mic is not working

This is out of scope of this library, perhaps try asking a raspberry pi forum? I honestly have no idea with this one
