### ISSUE TITLE
Configuring the module problems

### ISSUE THREAD

**Issue by SeriousOri** [dolanmiu/MMM-awesome-alexa#133]
If you know how to fix the issue, make a pull request instead.
Hi
After running this "npm run avs-token-helper"
I have to enter this here.
- Client ID
- Product ID
- Allowed return URL
What is "Redirect URI (allowed return URL)?"?

Is that this? "Http: // localhost: 3000 / authresponse"
I have that in the Developer Console.
If I have entered this, I get a URL which I should copy and paste.
When I paste this URL, I do not get an answer
In the address line this is "http: // localhost: 3000 / authresponse? Code = ANcuXXXzPLoOmVbNcFU & scope = alexa% 3Aall"

Redirect URI (allowed return URL)? http: // localhost: 3000 / authresponse? Code = ANcuXXXzPLoOmVbNcFU & scope = alexa% 3Aall
{ error_description: 'The request is missing a required parameter : code',
  error: 'invalid_request' }
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $

What am I doing wrong.

* [ ] Before submitting your issue add logs from your MagicMirror by running command `pm2 log MagicMirror`

**Comment by dolanmiu** [comment]
> Is that this? "Http: // localhost: 3000 / authresponse"
Yes, or whatever it is configured in your AVS control panel
> When I paste this URL, I do not get an answer
Your answer is `ANcuXXXzPLoOmVbNcFU`

**Comment by SeriousOri** [comment]
Hi @dolanmiu 
I also tried it that way. it's not working.
No idea why.

This is set on Amazon.

> Allowed return URLs?

https://www.example.com/login.php


http: // localhost: 3000 / authresponse

https: // localhost: 3000 / authresponse



-------------------------------------------
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm run avs-refreshToken-helper

- mmm-awesome-alexa@1.0.0 avs-refreshToken-helper /home/pi/MagicMirror/modules/MMM-awesome-alexa
- node avs-helper/avs-refreshToken-helper.js

1.) Welcome to the Amazon auth helper!
I will need four things from you:
- Authorization code from previous step
- Client ID
- Client secret
- Allowed return URL
[Press any key to continue]  
Authorization code (from previous step)? ANMXXXGjnMzyCSsjKo&scope=alexa%3Aall
Client ID? amzn1.application-oa2-client.XXXXXXX554128be9aecb90f740cf7
Client secret? 801c832cd6ee3bca19abc599cXXXXXXX0564445b969291d4692721f92d60
Redirect URI (allowed return URL)? http://localhost:3000/authresponse
{ error_description: 'The request has an invalid grant parameter : code',
  error: 'invalid_grant' }
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ 
--------------------------------------------
2.) 
[Press any key to continue] 
Authorization code (from previous step)? ANMDSXXXXXXCSsjKo
Client ID? amzn1.application-oa2-client.XXXXXX554128be9aecb90f740cf7
Client secret? 801c832cd6ee3bca19abc599cXXXXXXXX0564445b969291d4692721f92d60
Redirect URI (allowed return URL)? http://localhost:3000/authresponse
{ error_description: 'The request has an invalid grant parameter : code',
  error: 'invalid_grant' }
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $

**Comment by dolanmiu** [comment]
Your auth code is wrong, it should be `ANMXXXGjnMzyCSsjKo`, not `ANMXXXGjnMzyCSsjKo&scope=alexa%3Aall`

**Comment by SeriousOri** [comment]
Hi @dolanmiu 

thank you for your patience. It was not always the same. Well, now it worked.
got an access token and refresh token.
The refresh_Token I put in the config with the rest.
Now I have a deviceId there.
"deviceId": "YOUR_DEVICE_ID",
There is nothing about Device ID in Amazoin Developer.
I have there
ProductID Raspori
Amazon ID A8CEKPZXXXX
Client ID and client secret.

**Comment by dolanmiu** [comment]
can you run `npm start dev` and show me the logs/errors?

**Comment by SeriousOri** [comment]
Hi

> pi@raspberrypi:~ $ npm start dev
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-09-06T12_48_24_039Z-debug.log
pi@raspberrypi:~ $

**Comment by dolanmiu** [comment]
because it needs to be `/home/pi/MagicMirror/package.json`

**Comment by SeriousOri** [comment]
Hi @dolanmiu I think it's better if I start from the beginning :)


> pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
WARNING! Could not load config file. Starting with default configuration. Error                                                                                                                                                              found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa                                                                                                                                                             /node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.n                                                                                                                                                             ode'
Loading module helpers ...
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_m                                                                                                                                                             odules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/elect                                                                                                                                                             ron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_m                                                                                                                                                             odules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_m                                                                                                                                                             odules/snowboy/lib/node/index.js:132:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-awesome-alexa/node                                                                                                                                                             _modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/elect                                                                                                                                                             ron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_m                                                                                                                                                             odules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_m                                                                                                                                                             odules/snowboy/lib/node/index.js:132:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happene                                                                                                                                                             d. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://gi                                                                                                                                                             thub.com/MichMich/MagicMirror/issues
Launching application.

**Comment by SeriousOri** [comment]
Hello, yes, I have it installed. I really do not know where the mistake is. I will install everything from the beginning. I will contact you again.
Thank you for your patience.

**Comment by SeriousOri** [comment]
Again and again error messages.
If that is not normal I give up. :))

 pi@raspberrypi:~ $ cd ~/MagicMirror/modules
pi@raspberrypi:~/MagicMirror/modules $ cd MMM-awesome-alexa
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm run electron-rebuild

> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild --pre-gyp-fix

⠋ Searching dependency treeAn unhandled error occurred inside electron-rebuild
Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/node-abi/index.js:44:9)
    at new Rebuilder (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/rebuild.js:43:28)
    at Object.rebuild (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/rebuild.js:217:23)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/cli.js:100:33)
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/src/cli.js:5:58)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-09-06T21_50_00_105Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ 

[https://www.dropbox.com/s/07k4lni35p2u4hl/20180906_230504.jpg?dl=0](url)

[https://www.dropbox.com/s/fksbrygyg9oz1of/20180906_230654.jpg?dl=0](url)

[https://www.dropbox.com/s/01lg60ad73m4jap/Pip%20install%20Pyaudio2.txt?dl=0](url)

**Comment by dolanmiu** [comment]
odd, can you run this in the MMM-awesome-alexa folder:

```
npm install node-abi
```

Did some research here:

https://github.com/electron/electron/issues/12019

I may need to bugfix this

**Comment by dolanmiu** [comment]
I'll fix on the weekend

I'll pin all dependencies

**Comment by SeriousOri** [comment]
Hi @dolanmiu 

After entering the "npm install node-abi", run "npm run electron-rebuild" without error message.
Have everything installed.
How can I easily check Alexa is running?
I have a USB mic and normal speaker via jack.

When I enter "omxplayer -o alsa myAudioFile.mp3", it plays.
When I enter "arecord - format cd --duration 15 --channels 1 test.wav" I get an error message. "arecord: main: 788: audio open error: No such file or directory"

But I set microphone correctly. In nano ~ / .asoundrc

"pcm.! default {
         type hw
         card 0
}

ctl! default {
         type hw
         card 1
}
"
-------------------------------------------------------------------------------------------------------------------

pi@raspberrypi:~ $ cd MagicMirror
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: MMM-Fuel
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: MMM-awesome-alexa
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: MMM-Fuel
Starting module helper: MMM-Fuel
Connecting socket for: MMM-NowPlayingOnSpotify
Connecting socket for: MMM-awesome-alexa
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/XXXXXXXXXXXXX/private-18f854882cb4b123dc14265f                                                    9257820a/basic.ics - Interval: 300000
Refreshed access token because it has expired. Expired at: 17:51:03 now is: 17:51:06
Refreshed access token because it has expired. Expired at: 18:51:06 now is: 17:51:06
Refreshed access token because it has expired. Expired at: 18:51:06 now is: 17:51:08
Refreshed access token because it has expired. Expired at: 18:51:08 now is: 17:51:08
Refreshed access token because it has expired. Expired at: 18:51:08 now is: 17:51:09
(node:1108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [object Object]
(node:1108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not han                                        dled will terminate the Node.js process with a non-zero exit code.




https://www.dropbox.com/s/ih8hmbc8n0fu9lh/20180907_173131.jpg?dl=0
https://www.dropbox.com/s/7y502gga5x9juee/20180907_180726.jpg?dl=0

I do not want to annoy you. Please do not be angry. :)

**Comment by dolanmiu** [comment]
After this is merged in:

https://github.com/dolanmiu/MMM-awesome-alexa/pull/137

Can you delete /modules/MMM-awesome-alexa/node_modules

then `npm install` once again? I pinned all the dependencies

**Comment by dolanmiu** [comment]
Seems like theres no issues with the server, can u print screen the mirror logs?

I'll give you an example:

![screen shot 2018-09-08 at 22 18 34](https://user-images.githubusercontent.com/2917613/45258741-2a019780-b3b5-11e8-953b-c3d81f1429a8.png)

**Comment by SeriousOri** [comment]
Hi @dolanmiu 
Do you mean that?

https://www.dropbox.com/s/6qyd2vdswd1or54/20180909_165159.jpg?dl=0
https://www.dropbox.com/s/63glg8ht4fti7oc/20180909_165853.jpg?dl=0

**Comment by dolanmiu** [comment]
So it seems the module is working correctly with no errors, thats a good step

**Comment by SeriousOri** [comment]
Hi @dolanmiu 
Unfortunately, Alexa still does not work. It does`t react to the Wakeword "Alexa"
If I type this in Terminal ... "arecord -D plughw: 1,0 --duration = 3 test.wav && aplay test.wav" I can take a recording and play it. So the Micro works.

How can I check if Alexa really works?
And when it runs, where do I set the region and language?
Thank You

**Comment by SamerAl-khateeb** [comment]
**Ok.. So after reading all the issues on Github in this module and doing all the steps mentioned in all issues, I am still having a problem getting this to work. I see that many said that its a snowboy issue. and I searched for the snowboy folder and could not find it so I tried installing it and still ending up with the same error.**

pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm install --save snowboy
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cspell/configstore@git+https:/github.com/Jason3S/configstore.git#101c774d74ad458618ee26a9825bc1da1b958154" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/pi/.npm/_logs/2019-05-10T21_42_57_860Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $

**Also, I see that you have the same error "it does not contain a package.json file." how did you solve that @dolanmiu  @SeriousOri  ?**

**Comment by dolanmiu** [comment]
I have re-wrote the token helper tool and wrote a guide to eliminate all `snowboy` problems.

https://awesome-alexa.js.org/#/installation?id=configuration
