### ISSUE TITLE
Configuration Help Required

### ISSUE THREAD

**Issue by dh1201** [dolanmiu/MMM-awesome-alexa#134]
Following the installation and am stuck at the step:

```
Run avs-token-helper.js with npm run avs-token-helper
Follow the on screen instructions and give the script info it needs.
```

where do I get the info that it needs? i.e. Client ID, Product ID and Allowed return URL

Many thanks

**Comment by dolanmiu** [comment]
you get it from VS Control panel from Amazon

**Comment by dh1201** [comment]
Thanks for the info; however I have to say that I'm still confused.  How do I access the VS control panel?

**Comment by dolanmiu** [comment]
https://developer.amazon.com/alexa-voice-service

**Comment by cdnwolf** [comment]
Where do I find the port number to use?  I've tried finding the suggested port but cant get it to work.  Thanks

**Comment by dolanmiu** [comment]
https://awesome-alexa.js.org/#/installation?id=configuration

I have made a dedicated documentation website and re-wrote the tool to be much more user friendly
