### ISSUE TITLE
Disables mouse action on MMM

### ISSUE THREAD

**Issue by MichiMich** [dolanmiu/MMM-awesome-alexa#135]
Hello there,

I tried your module and its working just fine. After I wanted to try the module MMM-OnScreenMenu I realised that I am not able to click anything on the mirror (I also tried a few other modules with buttons to check that not the OnScreenMenu isnt working). The only way I could make a mouse click affect the modules on my mirror is with deactivating the MMM-awesome-alexa module in the config.js file. I already tried to switch off the "isSpeechVisualizationEnabled" but it did not change anything. Maybe its something with the z-index of your module?

Regards

**Comment by dolanmiu** [comment]
Yes the overlay of the z-index is very high, I will make clicks pass through

**Comment by dolanmiu** [comment]
Fixed:

https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/styles/global.css#L12
