### ISSUE TITLE
Has anyone tried multiple assistants on their MM?

### ISSUE THREAD

**Issue by mrprincehd** [dolanmiu/MMM-awesome-alexa#136]
So I finally got this Alexa to work *finally*, due to the limited functionality of this Alexa, I want to try out other assistants available for the MM; 
has anyone tried out multiple assistants installed on their MM? Do you think I would encounter conflicts with this alexa?

Also, as a replacement for reminder command, can I integrate these with dolanmiu's
`https://github.com/joanaz/AS-NoteTaker` and this
`https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs`

**Comment by mrprincehd** [comment]
Looking forward to your updates to this Alexa especially the streaming service and continuous conversation with Alexa, so far I’ve managed to find a workaround for my reminders with the help of Siri. Much more convenient since I use an iPhone. Probably my next addition is the facial recognition module.

**Comment by TheStigh** [comment]
@mrprincehd I'm using two voice assistants now :)

**Comment by dolanmiu** [comment]
Closing as issue is resolved.
