### ISSUE TITLE
Another config.js issue

### ISSUE THREAD

**Issue by tonytanjk** [dolanmiu/MMM-awesome-alexa#138]
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "0.0.0.0",
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.0.0/120"], 
                                                               // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.0.0/120"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
		    	module: 'MMM-Remote-Control',
                    	position: "bottom_left"
			// you can hide this module afterwards from the remote control itself
		},
		{	
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Singapore",
				locationID: "1880251",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "22c02d458b496016a2fea8fbfb0ee9f5"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Singapore",
				locationID: "1880251",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "22c02d458b496016a2fea8fbfb0ee9f5"
			}
		},
		{

 			module: 'MMM-connection-status',
        		 header: "Internet Connection",
         		position: 'top_left', // Or any valid MagicMirror position.
         		config: {
                            // See 'Configuration options' for more information.
                        }
		},
		{
			module: "MMM-Globe",
			position: "bottom_right",
			config: {
				style: 'geoColor',
				imageSize: 250,
				ownImagePath:'',
				updateInterval: 10*60*1000
			}
		},
		{
			module: "MMM-awesome-alexa",
			position: "bottom_bar",
			config: {
			      "wakeword": "Alexa",
			      "clientId": "amzn1.application-oa2-client.7240bc50da9542368afebbf1e16f3231",
			      "clientSecret": "0ac8e8cc512f39ec8fb6b8525b08d8187ecf6a4f243002143e6b256ff71f57d7",
			      "deviceId": "EchoDot",
			      "refreshToken": "Atzr|IwEBIN9R3HtLrDMFF9f921x-nyj_3u-QHPEFJ5Cmnz5s4O4IMpUNe13gY3VOUFvimpvyCcve3UZRwwjUNYPv9DM-_oy9EGKBUFs19oLPJNvmig9roig3x6aIZFVxBfc4TLMoh7Z6Hmas_-8qNMPvn4DZKoW2oyeJ4_FhCCed3FabjMrMzLEmgNqoCKuAppsK0WwXVRgSI8Y59pKs3n7wa2Y28qSgyjTyQI8OSkfu0Ie86YKaWWCpB6fNXPsQWrLkLPSO3-DrTIfyfFbqwo4ZJe2477ffiRajvPl9oJVJz7cGAUxdXHKSdtSdXKhpv5HRPNFcxrhq9TEWwlyPju2-shqSsxrjoqoeziIvLMjnR2UUAwSYdFaAbR5p4bDV7eg6DHAguSwuEkUgtBDGtqEUxSopnCzKYFfa3PJi0_NmSyoj2LIKzFTqkNcjw6HI8nMoPDHuJMP-4jnH6zd6ZbxpzHBUNwqZCkNE2Wj_SmiSEMHpxuC_InPqyipTUbMLkNne9QW_o4mYrwsSY4RPqn8Cfrk_MXz8Zewr_h2ypHA4hGrGUHEfng",
			      "visualisation": true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by tonytanjk** [comment]
Please help

**Comment by tonytanjk** [comment]
I keep on getting an eror like error wakeWord defined

**Comment by dolanmiu** [comment]
can you show me a print screen?

wakeWord is case sensitive, you typed "wakeword"

**Comment by tonytanjk** [comment]
It’s fine now I fixed it but may I know where you got your microphone USB

**Comment by dolanmiu** [comment]
https://www.amazon.co.uk/Demarkt-Microphone-Makio-Laptop-Desktop/dp/B01CQKCTSM/ref=sr_1_fkmr1_1?ie=UTF8&qid=1537036838&sr=8-1-fkmr1&keywords=USB+2.0+Mini+Microphone+for+Raspberry+Pi

**Comment by dolanmiu** [comment]
Try this:

https://github.com/jgarff/rpi_ws281x/issues/294

**Comment by tonytanjk** [comment]
What is pyaudio used for in MMM-awesome-alexa

**Comment by dolanmiu** [comment]
> May I ask what node.js version is MMM-awesome-Alexa compatible with?

I believe node 8

> What is pyaudio used for in MMM-awesome-alexa

pyaudio for mic

**Comment by tonytanjk** [comment]
I was able to install pyaudio but now there is import error saying No module named scipy

**Comment by tonytanjk** [comment]
It was while it was Downloading

**Comment by tonytanjk** [comment]
I used this sudo apt-get install portaudio19-dev. to download as I’m missing it

**Comment by tonytanjk** [comment]
Are you able to update it so users like me can use node 10

**Comment by dolanmiu** [comment]
Updated

All node versions should work now as `snowboy` is installed **seperately** from the module:

I have written a documentation site on how to install this module and how to fix snowboy issues:

https://awesome-alexa.js.org/#/installation?id=install-module
