### ISSUE TITLE
Invalid Grant Parameter

### ISSUE THREAD

**Issue by atimon** [dolanmiu/MMM-awesome-alexa#14]
When I run the code:

```
CLIENT_ID="amzn1.application-oa2-client.2ce85ab0db2d4e9..."
CLIENT_SECRET="4247e7121f974bd0dc964d99e3dfa445b8572e..."
CODE="ANudVcrBPTyYrgKMHhtu"
GRANT_TYPE="authorization_code"
REDIRECT_URI="https://localhost:9745/authresponse"

curl -X POST --data "grant_type=${GRANT_TYPE}&code=${CODE}&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&redirect_uri=${REDIRECT_URI}" https://api.amazon.com/auth/o2/token
```

i get the following error:
`{"error_description":"The request has an invalid grant parameter : code","error":"invalid_grant"}`
can anyone help me?

**Comment by dolanmiu** [comment]
Try to use the original article, maybe you will get some more luck with that:

https://miguelmota.com/blog/alexa-voice-service-authentication/

**Comment by NilSkilz** [comment]
I've got the same issue. The original guide doesn't help me - it's also quite out of date.
Any ideas or a workaround?

**Comment by NilSkilz** [comment]
In case anyone comes across this. I managed to get it working. One thing to note is that the 'code' you receive from Amazon expires when you try to use it, whether you receive back an access token or not. Also, the redirect_uri must be the same as the one you used to grant the initial code.

**Comment by dolanmiu** [comment]
Thanks @NilSkilz 

I will update the guide to make it more clear

Did the Alexa helper website not help at all?

**Comment by NilSkilz** [comment]
Just to document my process somewhat…

The Amazon UI has changed a fair bit when creating the ‘device’. But it’s easy enough to muddle through that part.
I used this page: https://sakirtemel.github.io/MMM-alexa/ <https://sakirtemel.github.io/MMM-alexa/> to generate the ‘Code’. You need to add https://sakirtemel.github.io/MMM-alexa/ <https://sakirtemel.github.io/MMM-alexa/> to the list of Redirect URLs for your device in the AVS product.

Once I had the ‘Code’ I used a REST console in Chrome (https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo <https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo>)

The url: https://api.amazon.com/auth/o2/token <https://api.amazon.com/auth/o2/token>
Select POST, Data Form then add your parameters for:
client_id
client_secret
code
grant_type
redirect_uri

I discovered two things at this point. 
1. The ‘Code’ generated is linked to the redirect_uri - so it needs to be the same one, in this case https://sakirtemel.github.io/MMM-alexa/ <https://sakirtemel.github.io/MMM-alexa/> 
(Use this as it’s url encoded: https%3A%2F%2Fsakirtemel.github.io%2FMMM-alexa%2F)
2. The code is single use, so if something goes wrong and it doesn’t work, you’ll need to generate a new code to try again.

From that I got the refresh_token.


I have to say, I’ve not got it working properly yet - but I haven’t had time to debug what’s going on (could be mic issue etc). So let me know if anyone does all this and gets it to work!

**Comment by atimon** [comment]
Thanks for the help! I now have my refresh token and have installed the module. It seems to be working fine but I can´t get it to speak. I have my microphone correctly set up and all, but no feedback from alexa

**Comment by dolanmiu** [comment]
No problem! Are you on a raspberry pi? That is pretty tricky to se up with the mic

**Comment by atimon** [comment]
Yeah I am… but the raspberry pi already recognises my mic and when I run rec t.wav it shows me the sound I’m making.
On 24 Aug 2017, at 18:20, Dolan <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem! Are you on a raspberry pi? That is pretty tricky to se up with the mic

**Comment by NilSkilz** [comment]
Are ur speakers working?

There’s a file u can use as a test in the module. Something like /Mmm-awesome-Alexa/resources/Alexa/. There’s an .mpeg file. I had to copy it to an mp3 to get it to play... so 
cp filename.mpeg filename.mp3

Then you should be able to run 
play filename.mp3. 

If u get no sound then that’s the problem.

**Comment by atimon** [comment]
Yes they do work, I can play test files from the internet and I can hear them.
On a side note, do you know how I can allow connections from the ips: 192.168.0.162 and 192.168.0.163 to my mirror? I have installed a remote control module and it denies connections form these Ip addresses,
thanks

On 24 Aug 2017, at 18:23, Rob Stokes <notifications@github.com<mailto:notifications@github.com>> wrote:

Are ur speakers working?

There’s a file u can use as a test in the module. Something like /Mmm-awesome-Alexa/resources/Alexa/. There’s an .mpeg file. I had to copy it to an mp3 to get it to play... so
cp filename.mpeg filename.mp3

Then you should be able to run
play filename.mp3.

If u get no sound then that’s the problem.

**Comment by dolanmiu** [comment]
Are you trying to remote control your PI? just use VNC

**Comment by cowboysdude** [comment]
Is there an actual 'HOW TO GET THIS TO WORK' guide anywhere?  There is so much information and misinformation here that it's VERY hard to tell what works and what doesn't...... Lots of problems to get a module to work.......

**Comment by adbang** [comment]
I'm still having issues getting the access code, I've tried all 3 ways listed and nothing works, I managed to get the initial code from https://sakirtemel.github.io/MMM-alexa/  but when i used ARC  to post a request I got 404 not found - <UnknownOperationException/>, When using the token from the URLmethod it;s difficult to decipher the token it seems massive compared to the one in the example.
Any help would be much appreciated

**Comment by adbang** [comment]
OK so I managed to get the refresh code, but when adding the config into the config.js the mirror doesn't start. Any ideas would be greatly appreciated.

**Comment by henrikra** [comment]
@adbang If you are running MagicMirror locally start it with `npm start dev` and looks for logs. If you are running MagicMirror installation on Raspberry run `pm2 logs 0` so you can see the same logs from running MagicMirror instance

**Comment by sobrien556** [comment]
Are there any updates on an easier way to get the refresh code? I am still having issues

**Comment by E3V3A** [comment]
@sobrien556 Yes, now there is. See #57

**Comment by haymaan** [comment]
hello ,
ive got the "refresh token must be set in the config before using swesome-alexa)
i fallow the---
 Select POST, Data Form then add your parameters for:
client_id
client_secret
code
grant_type
redirect_uri
ive add the url,,, but where/how to add the rest Client_id/Secret code and the other on the REST ..?
thanks
