### ISSUE TITLE
Connect to existing Amazon Alexa skills

### ISSUE THREAD

**Issue by pauldsmith1986** [dolanmiu/MMM-awesome-alexa#142]
After days of trying to get this working, I have finally got Alexa to work on my Magic Mirror. However, it doesn't see my existing skills, e.g. I ask her to turn off my bedroom light but she responds saying no skills have been added. Which isn't the case, as my Alexa Dot works fine. Can anyone advise, please?

**Comment by MMMveasy** [comment]
i have the same issue, skills not working. when i ask for Alexa for time or something else that's working. Did you found a solution?

**Comment by hacaro** [comment]
Same for me, any solution ?

**Comment by dolanmiu** [comment]
Have you tried configuring it here:

https://alexa.amazon.co.uk/spa/index.html

This module is quote novel, the streaming AVS (next gen) is not implemented yet, so it is quite limited right now
