### ISSUE TITLE
Breaking config.js with mmm-awesome-alex

### ISSUE THREAD

**Issue by berazzi** [dolanmiu/MMM-awesome-alexa#144]
I have the exact same issues as described in another issue here where whenever i paste in my mmm-awesome-alex config it breaks my entire config.js and my mirror says "Please create a config file".

I am fairly new to this game, so its been a bit of trial and error getting to here, but all the default modules provided by magicmirror works fine, and I have edited some of them to match my needs all done in steps to ensure everything works, and if not I know which change created the problem.

In regards to my problem it would be great to know if a wrong value, ie. the refreshtoken could cause this, or if only a syntax issue could create this issue, dont know if anyone knows about this?

That being said I have been all over this forum and tried alot of things, but none could fix the page. I also tried the things mentioned in #126 however it did not change anything.

My config.js:
```json
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: [], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
		    "module": "MMM-awesome-alexa",
		    "position": middle_center",
		    "config": {
		        "wakeWord": "Alexa",
		        "clientId": "amzn1.app.....",
		        "clientSecret": "ca8ed1ad......",
		        "deviceId": "magic01",
		        "refreshToken": "Atzr|IwEBII4S.....",
		        "visualization": false
		    }
		}
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Kommende helligdage",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "http://calen......"
					}
				]
			}
		},

	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

Please note this version, is basically just one of many I have tried from scraping the forum but none have worked.
I have tried to find anything in the log, but a pm2 log MagicMirror doesnt output anything??

Any ideas how to fix this?

**Comment by berazzi** [comment]
Maybe I should post some of the other constellations I have tested without success.

 {
                module: "MMM-awesome-alexa",
                position: "middle_center",
                config: {
                wakeWord: "Alexa",
                clientID: "amzn1.appli.....”
                clientSecret: "ca8ed1a....”
                deviceId: "magic01",
                refreshToken: "Atzr|IwEBII4S.....”
                lite: "false"
                isSpeechVisualizationEnabled: "true",
            }
                
},


{
    "module": "MMM-awesome-alexa",
    "position": "bottom_bar",
    "config": {
        "wakeWord": "Alexa",
        "clientId": "amzn1.appli.....",
        "clientSecret": "ca8ed1a....",
        "deviceId": "magic01",
        "refreshToken": "Atzr|IwEBII4S.....",
        "visualization": false
    }
}

Again I im fairly new to this, so I might have missed something obvious, so feel free to point your fingers :-P

**Comment by berazzi** [comment]
Hmm I just noticed that some of the " signs are different in what I have pasted above. Which I dont understand, as I have copied this from different sites, among other #126 as mentioned previously.

For instance here (clientID: "amzn1.appli.....”) I see two different types of " signs..I guess I have to tests this a bit back and forth.

**Comment by berazzi** [comment]
> You are missing a comma in the JSON in your first post on line 38
> 
> Edit:
> 
> There are a lot of errors,
> 
> Use this tool to resolve:
> 
> http://esprima.org/demo/validate.html

Thanks for the quick reply, much appreciated :-)

After my last post yesterday I made a few changes and now when running it through the validator I got only 1 error and after fixing it, it worked!
Though, when I say works I just mean it doesnt break my page anymore. I don't get anything from Alexa, so Ive started troubleshooting on that that.

**Comment by dolanmiu** [comment]
Closing because resolved
