### ISSUE TITLE
Not working but dont know why

### ISSUE THREAD

**Issue by berazzi** [dolanmiu/MMM-awesome-alexa#145]
I have installed the module, tested the audio and everything works as far as I can tell. However it doesnt work as nothing happens when saying "Alexa". I have tried the "pm2 log MagicMirror" to get some feedback on what could be the cause but all I get is: "[TAILING] Tailing last 15 lines for [MagicMirror] process (change the value with --lines option)"

There was no problems at installation, and since I cant get any log I have no idea how to proceed. Any suggestions?

**Comment by dolanmiu** [comment]
When you say Alexa, does a circle come up?

**Comment by berazzi** [comment]
Nope, no circle and nothing in the temp folder.

**Comment by dolanmiu** [comment]
That means your microphone is not set up properly

Type rec t.wav in the terminal

Can you record anything?

**Comment by berazzi** [comment]
You were right.. I tried to fix it with:

> export AUDIODEV=hw:1,0
> export AUDIODRIVER=alsa

but for some reason that only worked once, and now im just getting:

"rec FAIL formats: can't open input  `default': snd_pcm_open error: Device or resource busy" which i believe refers to my asoundrc which looks like this:

pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

**Comment by berazzi** [comment]
aplay -l 

**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

arecord -l

**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

**Comment by berazzi** [comment]
I have been going back and forth over this all day but cant get it to work so I started over, but to no avail.
So now when I do a "rec test.wav" I get: -bash: rec: command not found

If I do a arecord without specifying a device ( I get arecord: main:788: audio open error: No such file or catalog

However if I do a arecord with specifying the device (ie. arecord -D plughw:1,0 -d 3 test.wav) it works?!?!
In my /usr/share/alsa/alsa.conf I have set "defaults.ctl.card 1" as my arecord -l gives:
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

Shouldnt that be enough??

Also my asoundrc looks like this now:
pcm.!default {
    type hw
    card 0
}

ctl.!default {
    type hw
    card 1
}

**Comment by dolanmiu** [comment]
it needs the rec test.wav command to work because thats what this module uses under the hood

**Comment by berazzi** [comment]
Sorry for the delay, but have been trying a few things having started over twice... however now it have gotten alot worse.

**Comment by teodoro98** [comment]
I have the same problem.

`rec t.wav`
`rec WARN alsa: can't encode 16-bit Signed Integer PCM`
`rec FAIL formats: can't open output file t.wav: Permission denied`

but `sudo rec t.wav` works.

**Comment by dolanmiu** [comment]
Can you try asking the raspberry pi forum? I am not sure with this one
