### ISSUE TITLE
Black Screen that can't be exited out of unless rpi is reset

### ISSUE THREAD

**Issue by samzepstein** [dolanmiu/MMM-awesome-alexa#146]
Hi,

So I installed everything, audio and sound set up properly, but keep running into this black screen problem when I put the module into the config file. When I take it out it works fine. I also have AlexaPi installed, not sure if that makes a difference.

Here is my code below for the config (replaced Api keys and IDs with dummy text):

```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "imperial",

	modules: [
		{
			module: "alert",
		},

		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "My Calendar",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
					},
					{
						symbol: "My Calendar",
						url: "https://calendar.google.com/mycalendar"
					}
				]
			}
		},

		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Los Angeles",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "API KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Los Angeles",
				locationID: "5128581",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "API KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
		{
		  module: "MMM-NowPlayingOnSpotify",
		  position: "bottom_right",
		
		  config: {
		    clientID: "API KEY",
		    clientSecret: "API KEY",
		    accessToken: "API KEY",
		    refreshToken: "API KEY"
  			}
},
	{
	    "module": "MMM-awesome-alexa",
	    "position": "bottom_left",
	    "config": {
	        "wakeWord": "Alexa",
	        "clientId": "ID",
	        "clientSecret": "ID",
	        "deviceId": "deviceID",
	        "refreshToken": "ID,
	        "lite": false,
	        "isSpeechVisualizationEnabled": true
	}

},


	{
	  //disabled:true,
	  module: "MMM-AVStock",
	  position: "top_left", //"bottom_bar" is better for `mode:ticker`
	  config: {
	    apiKey : "API", // https://www.alphavantage.co/
	    timeFormat: "YYYY-MM-DD HH:mm:ss",
	    symbols : ["VT", "VUG", "VBK"],
	    alias: ["", "", ""], //Easy name of each symbol. When you use `alias`, the number of symbols and alias should be the same. If value is null or "", symbol string will be used by default.
	    tickerDuration: 60, // Ticker will be cycled once per this second.
	    chartDays: 90, //For `mode:series`, how much daily data will be taken. (max. 90)
	    poolInterval : 1000*15, // If your AV account is free, at least 13 sec is needed.
	    mode : "table", // "table", "ticker", "series"
  }
},
{
	  module: 'MMM-MyCommute',
	  position: 'top_left',
	  config: {
	    apikey: 'apikey',
	    origin: 'address',
	    startTime: '00:00',
	    endTime: '23:59',
	    hideDays: [0,6],
	    destinations: [
	      {
	        destination: 'address',
	        label: 'Work',
	        mode: 'driving',
	        color: '#82E5AA'
	      },
	      {
	        destination: 'address',
	        label: 'Alliance',
	        mode: 'driving'

	      },
	      {
	        destination: 'address',
	        label: 'Home',
	        mode: 'driving'
      }
    ]
  }
}



	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```
`

I also noticed that I was getting errors when running npm run electron-rebuild but not npm run --electron-rebuild. I already installed node-abi as well. My node version is v11. 6. 0

```
`pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm run electron-rebuild

> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild --pre-gyp-fix

✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 2.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/node-abi/index.js:43:9)
    at _callee6$ (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:152:37)
    at tryCatch (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:96:21)
    at Generator.tryCatcher (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:97:49)
    at /home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:201:15
    at _rebuild (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:613:18)
    at rebuild (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/rebuild.js:624:28)
    at _callee$ (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/lib/cli.js:160:45)
    at tryCatch (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:337:22)
    at Generator.prototype.(anonymous function) [as next] (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/electron-rebuild/node_modules/regenerator-runtime/runtime.js:96:21)
    at Generator.tryCatcher (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_modules/bluebird/js/release/generators.js:97:49)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! mmm-awesome-alexa@1.0.0 electron-rebuild: `electron-rebuild --pre-gyp-fix`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the mmm-awesome-alexa@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-04T06_38_24_569Z-debug.log


pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm run --electron-rebuild
Lifecycle scripts included in mmm-awesome-alexa:
  test
    npm run lint

available via `npm run-script`:
  build
    webpack --progress --profile --bail --display-error-details
  dev
    npm run build -- --watch --mode development
  electron-rebuild
    electron-rebuild --pre-gyp-fix
  lint
    tslint --project .
  node-pre-gyp
    node-pre-gyp clean configure build
  test-rec
    bash test-rec.sh
  spell
    cspell src/**/*.ts
  style
    prettier -l src/**/*.ts
  avs-token-helper
    node avs-helper/avs-token-helper.js
  avs-refreshToken-helper
    node avs-helper/avs-refreshToken-helper.js
  build.avs-helper
    tsc --p tsconfig.avs-helper.json`
```

I tried pulling logs on the Mirror but I get a black screen and the pi freezes. 

Also from npm dev:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm start dev
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-01-04T06_56_17_284Z-debug.log

```

I also checked and saw that my temp file was empty. Any help on troubleshooting would be amazing thank you!!

**Comment by samzepstein** [comment]
Thank you for the quick response. I put my config code in espirma and it said it was syntactically valid. Also, I ran npm start dev in the MagicMirror folder and it freezed the developer console and I had to restart the pi. Still getting the black screen. 


When I take out the MMM-awesome-alexa module, the mirror loads fine. Any reason why this could happen? 

<img width="964" alt="screen shot 2019-01-04 at 9 29 39 am" src="https://user-images.githubusercontent.com/38083036/50701781-b76f9400-1003-11e9-9f94-4961ef74afe7.png">

Here is what I get when I run npm start dev in the MagicMirror folder

<img width="976" alt="screen shot 2019-01-04 at 9 38 57 am" src="https://user-images.githubusercontent.com/38083036/50702097-cb67c580-1004-11e9-8fab-ebbdf9e6013b.png">

<img width="1423" alt="screen shot 2019-01-04 at 9 39 06 am" src="https://user-images.githubusercontent.com/38083036/50702178-fce09100-1004-11e9-96de-fbe28cb8d9a7.png">

**Comment by dolanmiu** [comment]
From what I can see, it cannot find `snowboy`

Try to run `npm run electron-rebuild`, or downgrade your node version, what is it currently?

**Comment by tonytanjk** [comment]
hi i ran into the same issue as him as well i'm running node version 8 but it seems that electron-rebuild can't work for me and i instead manually installed snowboy but even if its installed,They gave me that they can't find node-abi ver 2.0.16 which is an invalid version which i may be wondering if you made an error in this module?

**Comment by tonytanjk** [comment]
Idk why but I thought that was just to state what is included in the script and not really the true electron rebuild as dolanmiu said that we should only use npm run electron rebuild but not npm run - -electron-rebuild

**Comment by tonytanjk** [comment]
And the module itself is not supporting nodejs ver. 11 so I have no idea how you get past the npm install =prod

**Comment by tonytanjk** [comment]
I found a way to load the modules but now I’m unsure if the awesome Alexa module is working but yea I found a file which is an arm file and I renamed it to electron-v2.0-linux-arm. Which mainly first solve the black screen issue but idk if the module for Alexa works as now it’s a temporary fix before dolanmiu decides to fix this

**Comment by tonytanjk** [comment]
I have confirmed that Alexa module now works perfectly

**Comment by samzepstein** [comment]
@tonytanjk amazing! So to confirm, the Alexa module is working for you now with the visualization? Also how did you manually install snowboy and find that arm file?

Thanks~

**Comment by tonytanjk** [comment]
I actually did not have to install snow boy since npm run electron-rebuild will do that but I needed to find a solution and thought that manually installing snow boy would work but it didn’t instead I done something else to make it work which is already in the comments.Good luck

**Comment by berazzi** [comment]
I have exactly the same issue as @samzepstein. 

After having had problems with being able to install everything, I got that resolved partly thanks to @tonytanjk but now I am stuck with the same problem. My screen is simply black whenever I include the mmm-alexa module in the config.
If I leave it out, all is fine.
I have tried

> First open terminal and go to MMM-awesome-Alexa
> Then write this commands
> Npm install npm@latest -g
> Once it’s done install
> Npm install node-abi
> Then install
> Npm install electron-rebuild
> After all of it is done do
> Npm run electron rebuild it should be successful.

As stated by @tonytanjk and all of the commands went off fine, but I still have the problem. Also I do not have a file called "node-v57-liinux-arm".

Any suggestions?

**Comment by tonytanjk** [comment]
It’s node-v57-linux-arm but should be ok 
. imma try to show you where to get the folder since your able to go thru all of the installations I asked from.

**Comment by berazzi** [comment]
just to be clear, simply connect a keyboard and press ctrl+alt? Because that didnt do anything?

You mentioned the folder with the node-v57-linux-arm should be MagicMirror/modules/MMM-awesome-Alexa/node_modules/snowboy right?

**Comment by tonytanjk** [comment]
Yes  and I would need to check if ctrl+alt allows me to get a way to minimise screen looks like I’m forgetting it again :(

**Comment by bachoo786** [comment]
@tonytanjk when i run the last command i.e. npm install electron-rebuild I get this:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm install electron-rebuild
+ electron-rebuild@1.8.4
added 4 packages from 1 contributor, updated 4 packages, moved 1 package and audited 6804 packages in 51.215s
found 9 vulnerabilities (1 low, 8 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
```
does that mean something is wrong? what can I do?

**Comment by tonytanjk** [comment]
@bachoo786 no it actually means you successfully installed electron rebuild which is a good way to start

**Comment by bachoo786** [comment]
also when I run npm start dev in MagicMirror folder why does it get stuck in "Launching application"? I dont get any logs after that. Please see below:

```
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.6.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
No helper found for module: random_quotes.
Initializing new module helper ...
Module helper loaded: MMM-homeassistant-sensors
Initializing new module helper ...
Module helper loaded: MMM-UKNationalRail
No helper found for module: MMM-TFL.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ...
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Connecting socket for: MMM-homeassistant-sensors
Connecting socket for: MMM-UKNationalRail
MMM-UKNationalRail helper started ...
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Whoops! There was an uncaught exception...
{ Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at new Server (/home/pi/MagicMirror/js/server.js:27:9)
    at /home/pi/MagicMirror/js/app.js:219:18
    at loadNextModule (/home/pi/MagicMirror/js/app.js:168:5)
    at /home/pi/MagicMirror/js/app.js:163:6
    at Class.loaded (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:19:3)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080 }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

```

**Comment by bachoo786** [comment]
@tonytanjk after following your method of updating and getting rid of the black screen my MM broke and wouldnt be found by pm2 until I reboot my rpi. I had to do a fresh install of raspbian stretch and mm.

@dolanmiu If there are better instructions on installing this module it would be great.

**Comment by tonytanjk** [comment]
I did not reference you to update your electron rebuild at all. @smartmirrorkits referenced it to you

**Comment by tonytanjk** [comment]
I got these types of issue which you had before but it didn’t affect the Smart Mirror program at all. I think you should save your config.js file and do a fresh installation of MagicMirror again and use your old config file. See if it would work like try and error. I’m a student in Singapore so I would not really be too active in github due to time collision so might expect me to not answer for quite a while.

**Comment by MoritzHeinz** [comment]
Having the same error Error: 
Cannot find module 'snowboy'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:1382)
    at r (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:279)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:5363)
    at r (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:279)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-awesome-alexa/node_helper.js:1:5735)
Whoops! There was an uncaught exception...

**Comment by tonytanjk** [comment]
Sorry I won’t be able to answer now as I do not have access to my raspberry pi and this whole week including next week I have exams so I would not be able to help. Sorry for the inconvenience.

**Comment by MoritzHeinz** [comment]
Don't worry, thanks for the reply anyway :)

**Comment by SamerAl-khateeb** [comment]
> I have exactly the same issue as @samzepstein.
> 
> After having had problems with being able to install everything, I got that resolved partly thanks to @tonytanjk but now I am stuck with the same problem. My screen is simply black whenever I include the mmm-alexa module in the config.
> If I leave it out, all is fine.
> I have tried
> 
> > First open terminal and go to MMM-awesome-Alexa
> > Then write this commands
> > Npm install npm@latest -g
> > Once it’s done install
> > Npm install node-abi
> > Then install
> > Npm install electron-rebuild
> > After all of it is done do
> > Npm run electron rebuild it should be successful.
> 
> As stated by @tonytanjk and all of the commands went off fine, but I still have the problem. Also I do not have a file called "node-v57-liinux-arm".
> 
> Any suggestions?

Hi Would you please help me with this, I am having the same issue with black screen after adding the config to my magic mirror. 
I did the following as you suggested
cd ~/MagicMirror/modules/MMM-awesome-alexa 
$ sudo npm install npm@latest -g
but then once I did this step npm install node-abi I am getting error but i do not know why! any idea? here is what I am getting:

pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo npm install npm@latest -g
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.9.0
added 54 packages from 9 contributors, removed 15 packages and updated 47 packages in 58.591s
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm install node-abi
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cspell/configstore@git+https:/github.com/Jason3S/configstore.git#101c774d74ad458618ee26a9825bc1da1b958154" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-29T21_11_00_766Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo npm install node-abi
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cspell/configstore@git+https:/github.com/Jason3S/configstore.git#101c774d74ad458618ee26a9825bc1da1b958154" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-29T21_11_42_946Z-debug.log

**Comment by tonytanjk** [comment]
Can you try to find the file node-v57-Linus-arm

**Comment by tonytanjk** [comment]
Node-v57-linux-arm*

**Comment by SamerAl-khateeb** [comment]
> Node-v57-linux-arm*

Which folder should have this file?

**Comment by tonytanjk** [comment]
Here is how to access and change the name folders.
Go to MagicMirror/modules/MMM-awesome-Alexa/node_modules/snowboy and find a file called node-v57-linux-arm and change it to electron-v2.0-linux-arm.

Please manually find it and change it.

**Comment by SamerAl-khateeb** [comment]
Sorry my previous comment was deleted by mistake, here is the question I have:
I am have the problem of black screen once I add the config to the file. I followed the steps you mentioned:
cd ~/MagicMirror/modules/MMM-awesome-alexa 
$ sudo npm install npm@latest -g
but once I run  npm install node-abi I get an error. Here is what I am getting:

pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo npm install npm@latest -g
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.9.0
added 54 packages from 9 contributors, removed 15 packages and updated 47 packages in 58.591s
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm install node-abi
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cspell/configstore@git+https:/github.com/Jason3S/configstore.git#101c774d74ad458618ee26a9825bc1da1b958154" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-29T21_11_00_766Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo npm install node-abi
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cspell/configstore@git+https:/github.com/Jason3S/configstore.git#101c774d74ad458618ee26a9825bc1da1b958154" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-29T21_11_42_946Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ sudo npm install node-abi

**Comment by tonytanjk** [comment]
Hmm I will try to get it checked once I’m at home? Because now I’m going to school and do not have access to the pi I will check it for you and see if I get the same mistake later on?

**Comment by tonytanjk** [comment]
I would suggest that you can go through the past comments and try to find the answers there for now.  Thank you

**Comment by tonytanjk** [comment]
Though most people would be thinking why a 13 year old kid would be working on complex raspberry pi stuff but I love them anyways and I love to help people who are determined to get their Projects working how the way they wanted.

**Comment by SamerAl-khateeb** [comment]
I really appreciate your help. I think snowboy is not installed because I can not find the folder inside MagicMirror/modules/MMM-awesome-Alexa/node_modules/snowboy but not sure how to install it or where should I install it. Any idea?
Good luck in your school.

**Comment by SamerAl-khateeb** [comment]
Ok I run 
npm run electron-rebuild

and it seems to be installed

pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm run electron-rebuild

> mmm-awesome-alexa@1.0.0 electron-rebuild /home/pi/MagicMirror/modules/MMM-awesome-alexa
> electron-rebuild --pre-gyp-fix

✔ Rebuild Complete

and still a black screen!

**Comment by tonytanjk** [comment]
Ok the rebuild is a good start

**Comment by tonytanjk** [comment]
I would wish that github would allow pictures or videos to be sent out but sadly they do not have it

**Comment by tonytanjk** [comment]
Im omw home right now and will get to my raspberry pi ASAP.

**Comment by SamerAl-khateeb** [comment]
Thank you very much for doing this, I am almost giving up on this project. Alexa does not seem to like me 😂

**Comment by tonytanjk** [comment]
Nah it’s just some errors on the MagicMirror files itself hopefully @dolanmiu can fix these errors and put in a new release.

**Comment by SamerAl-khateeb** [comment]
Ok.. So after reading all the issues on Github in this module and doing all the steps mentioned in all issues, I am still having a problem getting this to work. I see that many said that its a snowboy issue. and I searched for the snowboy folder and could not find it so I tried installing it and still ending up with the same error.

pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $ npm install --save snowboy
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/cspell/configstore@git+https:/github.com/Jason3S/configstore.git#101c774d74ad458618ee26a9825bc1da1b958154" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-05-10T21_42_57_860Z-debug.log
pi@raspberrypi:~/MagicMirror/modules/MMM-awesome-alexa $

**Comment by dolanmiu** [comment]
I have written a documentation site on how to install this module and how to fix snowboy issues:

https://awesome-alexa.js.org/#/installation?id=install-module

**Comment by tonytanjk** [comment]
Thanks for the work @dolanmiu

**Comment by dolanmiu** [comment]
My pleasure

If there are any issues, open a new issue, this issue is getting out of hand and off topic

Thanks

**Comment by tonytanjk** [comment]
Oh @dolanmiu I remembered most people had a issue with pyaudio and needed to install something to make sure the installation was a success could you add that in as well?

**Comment by tonytanjk** [comment]
Like sudo apt install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg libav-tools

**Comment by tonytanjk** [comment]
For pip install pyaudio

**Comment by dolanmiu** [comment]
Is this sufficient?

https://awesome-alexa.js.org/#/installation?id=raspberry-pi-specific-dependencies

**Comment by tonytanjk** [comment]
Should be eventhough the code I stated would probably be added but maybe for those who could not do pip install  pyaudio since I also had the error despite the installation of python 3

**Comment by dolanmiu** [comment]
Ok, I will add that in

**Comment by tonytanjk** [comment]
Ok thank you
