### ISSUE TITLE
couldn't able to clear the error 

### ISSUE THREAD

**Issue by prithesh990** [dolanmiu/MMM-awesome-alexa#149]
please checkout the following error and config file shown below
error
*********************************
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'snowboy'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'snowboy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/prithesh_chowta/Downloads/AI-Mirror/modules/MMM-awesome-alexa/node_helper.js:1:1289)
    at r (/home/prithesh_chowta/Downloads/AI-Mirror/modules/MMM-awesome-alexa/node_helper.js:1:186)
    at Object.<anonymous> (/home/prithesh_chowta/Downloads/AI-Mirror/modules/MMM-awesome-alexa/node_helper.js:1:5270)
    at r (/home/prithesh_chowta/Downloads/AI-Mirror/modules/MMM-awesome-alexa/node_helper.js:1:186)
    at Object.<anonymous> (/home/prithesh_chowta/Downloads/AI-Mirror/modules/MMM-awesome-alexa/node_helper.js:1:5642)
    at r (/home/prithesh_chowta/Downloads/AI-Mirror/modules/MMM-awesome-alexa/node_helper.js:1:186) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
*******************************
config.js file:

var config = {
    address: "localhost",
    port: 8080,
    ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
                                                           // or add a specific IPv4 of 192.168.1.5 :
                                                           // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
                                                           // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
                                                           // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

    language: "en",
    timeFormat: 24,
    units: "metric",

    modules: [
        {
            module: "alert",
        },
        {
            module: "updatenotification",
            position: "top_bar"
        },
        {
            module: "clock",
            position: "top_left"
        },
        {
            module: "calendar",
            header: "Indian Holidays",
            position: "top_left",
            config: {
                calendars: [
                    {
                        symbol: "calendar-check",
                        url: "webcal://www.calendarlabs.com/templates/ical/India-Holidays.ics"
                    }
                ]
            }
        },
        {
            module: "compliments",
            position: "lower_third"
        },
        {
            module: "currentweather",
            position: "top_right",
            config: {
                location: "Mangalore, IN",
                locationID: "1263780",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
                appid: "8bf1c638dfe5cf9f035bb3640ffa15e1"
            }
        },

        {
            module: "weatherforecast",
            position: "top_right",
            header: "Weather Forecast",
            config: {
                location: "Mangalore, IN",
                locationID: "1263780",  //ID from https://openweathermap.org/city
                appid: "8bf1c638dfe5cf9f035bb3640ffa15e1"
            }
        },
        {
            module: "newsfeed",
            position: "bottom_bar",
            config: {
                feeds: [
                    {
                        title:"The Times Of India",
                        url: "http://timesofindia.indiatimes.com/rssfeedstopstories.cms"
                    }
                ],
                showSourceTitle: true,
                showPublishDate: true
            }
        },
                {
                        module: "MMM-awesome-alexa",
                       position: "bottom_bar",
                        config: {
                                 wakeWord: "Alexa",
                                 clientId: "amzn1.application-oa2-                  client.bbed1cd3b2634552a482c886c02b2a25",
                                 clientSecret: "d58385a14fe2ce9e6e292cd9ca6c6ba7f387748d56dfaad9999f794a9a16495f",
                                 deviceId: "AImirror",
                                 refreshToken: "Atzr|IwEBIDVQyZ8pCxfxKJXDB2GQCNUoqAJqGYGaSpBav3IWlPmyt_rPMZs3mxgwWqwVnNoTVra9iPHy6dT_6oI57jPD7gl00lyfK2-wc7F6uAglGrS7qk603SD_n4FAi-heN6HRYwMpF-BCTATkck3fyVJp5UXBCV_F6tYa58kFHwdYqFoRgfNMsrfYSSQwtfR441j60PaWMlOyV-4GSdWUcXoUsuPhs114Ynl9ayYHJ_C-19spXF7feiQ9jrvScWzHZaSyTudy0m5fFcQstF5_wAWV9UGV-LsCg06aZsaWR5FwBpHVFbF-mv9JM90rWUb7S_-qmIzXjYh9nFZRJ_iMH_580-YJ6dqZNcbKNG3Zx0KbjNfKMwX5oey4Jyf8F164wHDbEclgK9rlBcPD1OGbWAq3GoQ6kA5qi9D4WqWBThoeYwR9Xh_M4MwUZagyoHebfgezcpOrLAGIQnOeDpZy3hBFRWo8I8E8xKko5SF_Cfv_obLYGrig0j2q26Ha5fTPIt61Fm5BwremZmy50NlMjoD9m6b8UF026_BHRj-79hjHvlGDoA",
                                 lite: false,
                                 isSpeechVisualizationEnabled: true
                                 }
                }
    ]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by dolanmiu** [comment]
I have written a documentation site on how to install this module and how to fix snowboy issues:

https://awesome-alexa.js.org/#/installation?id=install-module
