### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by ToxicWaste95** [dolanmiu/MMM-awesome-alexa#15]
Hi Having some issues, well 3 I think, i don't have a mic yet so cannot really test functionality.

1 - Running the ./auth_code.sh script
I get the following.... 
Couldn't get a file descriptor referring to the console

2 - Running the web url for the token just flashes the screen from black to the website but I cannot pause or see what it is saying, so not sure if the token stuff is right?
https://magic-mirror-avs.github.io/Alexa-Web-Helper/

3 - When starting up MMM I get the following using npm start, the console opens and the rest runs, but shows this at the end.......
(node:4059) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: [object Object]
(node:4059) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

**Comment by dolanmiu** [comment]
the error you are experiencing at 3 is probably due to not having a `refresh token`

I am not sure how to help you with the refresh token, it works fine for me

Maybe try the original article to see if you have any luck?

https://miguelmota.com/blog/alexa-voice-service-authentication/

**Comment by ToxicWaste95** [comment]
I tried that and thats when I get problem number 2
If I press ctrl+alt+del and bring up a whole screen of task managers then I can see the website behind them all, but as soon as I click on the website the screen goes black again

**Comment by dolanmiu** [comment]
Press <kbd>ALT</kbd>, then the task bar should come up, then press minimise

**Comment by ToxicWaste95** [comment]
Okay got the page to work for me capture my details and then click create, Signs me into Amazon, Click Okay to grant access to the PI to access Alexa and then bang....We are sorry! An error accured when we tried to process your request ????

**Comment by raddyroro** [comment]
I'm having the same issue @ToxicWaste95 Whenever I enter my details and try to login I get an error page. stating:
"We're sorry!An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly."
Not sure if its an issue on my end or Amazon's end, got any solutions or experienced this @dolanmiu

**Comment by dolanmiu** [comment]
Maybe Amazon does not support your region perhaps? I do not get this issue. I live in the UK

**Comment by cowboysdude** [comment]
I have figured out that you have to pick the option on the left..... for some strange reason when you choose the one on the right you get that error....... I got it several times then chose the other option and it worked.  It's more than likely an Amazon issue that they have no intention on fixing ;)
