### ISSUE TITLE
getting error for npm install --only=prod

### ISSUE THREAD

**Issue by prithesh990** [dolanmiu/MMM-awesome-alexa#155]
i have completed all the steps but got this error.......
please help asap
> snowboy@1.2.0 preinstall /home/pi/MagicMirrordemo/modules/MMM-awesome-alexa/node_modules/snowboy
> npm install node-pre-gyp

npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }
npm ERR! path /root/.npm/_cacache/index-v5/f6/d3/856f4e146dc3e8cb995652c4d6a1e16806d6bca7e87878fd9046e55ea74f
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/root/.npm/_cacache/index-v5/f6/d3/856f4e146dc3e8cb995652c4d6a1e16806d6bca7e87878fd9046e55ea74f'
npm ERR!  { Error: EACCES: permission denied, open '/root/.npm/_cacache/index-v5/f6/d3/856f4e146dc3e8cb995652c4d6a1e16806d6bca7e87878fd9046e55ea74f'
npm ERR!   cause: 
npm ERR!    { Error: EACCES: permission denied, open '/root/.npm/_cacache/index-v5/f6/d3/856f4e146dc3e8cb995652c4d6a1e16806d6bca7e87878fd9046e55ea74f'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'open',
npm ERR!      path: '/root/.npm/_cacache/index-v5/f6/d3/856f4e146dc3e8cb995652c4d6a1e16806d6bca7e87878fd9046e55ea74f' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: EACCES: permission denied, open \'/root/.npm/_cacache/index-v5/f6/d3/856f4e146dc3e8cb995652c4d6a1e16806d6bca7e87878fd9046e55ea74f\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/root/.npm/_cacache/index-v5/f6/d3/856f4e146dc3e8cb995652c4d6a1e16806d6bca7e87878fd9046e55ea74f' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! snowboy@1.2.0 preinstall: `npm install node-pre-gyp`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the snowboy@1.2.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-22T14_39_37_231Z-debug.log

**Comment by hco125** [comment]
`npm install --only=prod` resulted in the errors in this log file:
[2019-02-24T18_32_35_910Z-debug.log](https://github.com/dolanmiu/MMM-awesome-alexa/files/2898232/2019-02-24T18_32_35_910Z-debug.log)

And the next step, `npm run electron-rebuild` came up with the errors in this log:
[2019-02-24T18_36_35_145Z-debug.log](https://github.com/dolanmiu/MMM-awesome-alexa/files/2898236/2019-02-24T18_36_35_145Z-debug.log)

**Comment by prithesh990** [comment]
m too getting errors

**Comment by braunprinz** [comment]
Hello
Is there any solution to this issue ?

**Comment by SmakyTaky** [comment]
anybody?

**Comment by hco125** [comment]
Nothing

**Comment by harrykendal** [comment]
Same problem too

**Comment by SmakyTaky** [comment]
any solution to this issue? I was able to get snowboy installed (1.3.1) if I run "install --save snowboy" from MagicMirror folder.. however if I try this from MMM-awesome-alexa folder I get the error above. Seems this is more ralated to this module and not my npm or node configuration.

**Comment by OliverLundgren** [comment]
Hi! I hade the same problem and with a lot of hours reaserching i managed to solve the problem.
I had to downgrade my NodeJS. Then i downloaded Snowboy!
Followed this guide, https://www.instructables.com/id/Install-Nodejs-and-Npm-on-Raspberry-Pi/ , but with some modifications of course!
Tell me if this helps :) Have fun!

**Comment by prithesh990** [comment]
I had already tried that to downgrade npm but for snowboy how to install or connect with mirror can you please tell the instructions

**Comment by Nyxholas** [comment]
Can someone please fix these issues for the love of god.

**Comment by dolanmiu** [comment]
Due to `snowboy` again...

I have written a documentation site on how to install this module and how to fix `snowboy` issues:

https://awesome-alexa.js.org/#/installation?id=install-module

**Comment by leyts** [comment]
I have found a fix.

1. `npm install -g n` - Installs a simple NPM installer.
2. `sudo n 6.17.1` - Installs a supported version of Node. Downloaded from [https://nodejs.org/en/download/releases/](url).
3. Go to [https://awesome-alexa.js.org/#/installation](url) and follow the Install Module instructions.
