### ISSUE TITLE
No Text Visualization 

### ISSUE THREAD

**Issue by Raiv3n** [dolanmiu/MMM-awesome-alexa#156]
The module can hear me and also answers to me, but there is no visual feedback. 
isSpeechVisualizationEnabled is enabled. There is just the white dot in the middle when i start talking but no text.

**Comment by harrykendal** [comment]
Im having the same issue.

**Comment by tylertech234** [comment]
Ah an I was just troubleshooting the same thing after finally getting this going. It would be very awesome if it did have text like that! So what is the difference between having Visualization true vs false in the config?

**Comment by dolanmiu** [comment]
The visualisation flag is the breathing circle
