### ISSUE TITLE
failed to install snowboy

### ISSUE THREAD

**Issue by krazylol** [dolanmiu/MMM-awesome-alexa#157]
https://gyazo.com/4aafead2b8dbd90e87dbd11209f16bf9

**Comment by OliverLundgren** [comment]
Hi! I hade the same problem and with a lot of hours reaserching i managed to solve the problem.
I had to downgrade my NodeJS. Then i downloaded Snowboy!
Followed this guide, https://www.instructables.com/id/Install-Nodejs-and-Npm-on-Raspberry-Pi/ , but with some modifications of course!
Tell me if this helps :) Have fun!

**Comment by Nyxholas** [comment]
@krazylol 
sudo npm cache clean -f
sudo npm install -g n
sudo n 8.0.0

**Comment by dolanmiu** [comment]
Wrote proper install instructions on how to fix snowboy issues:

https://awesome-alexa.js.org/#/installation?id=install-module
