### ISSUE TITLE
Alexa only responds with: 'sorry, I'm not sure about that'

### ISSUE THREAD

**Issue by anthonyka** [dolanmiu/MMM-awesome-alexa#16]
how can i fix this ? whatever i ask, she responds with ' sorry, I'm not sure about that'.
It may be the quality of my mic, I am not sure tho.

**Comment by dolanmiu** [comment]
Next time when Alexa says `sorry, I'm not sure about that`, could you check the `MagicMirror/modules/MMM-awesome-alexa/temp` folder, and check if your voice can be heard there?

**Comment by anthonyka** [comment]
It was actually an error with my mic. It now works ! is it possible to get images to show on the mirror through alexa ? eg: "alexa, show me a picture of ..."

**Comment by dolanmiu** [comment]
Good to know it works!

I never considered putting pictures on the magic mirror, but its a good idea, one step closer to Iron Man

Perhaps it could be a future feature
