### ISSUE TITLE
Alexa doesn't react after nothing was said the time before

### ISSUE THREAD

**Issue by dv46** [dolanmiu/MMM-awesome-alexa#160]
Alexa finally works now, but when I don't say anything or someone says something at the same time and she doesn't understand it, she just doesn't say anything anymore and also doesn't react to the wakeword anymore. She is stuck in the "busy" state.
Thanks for help!

**Comment by dolanmiu** [comment]
This is due to Google Chrome's new behavior, explained here (and how to fix):

https://awesome-alexa.js.org/#/installation?id=modifying-magicmirror-electron
