### ISSUE TITLE
PLease, need some guideing to set up Alexa account

### ISSUE THREAD

**Issue by TheStigh** [dolanmiu/MMM-awesome-alexa#161]
@dolanmiu Could you please provide some updated guides how to set up the rest from the moment I've gotten my client- and secret ID and created a Product. I've added the "Allowed origins: **http://localhost:9745**" and "Allowed return URLs : **http://localhost:9745/authresponse**"?

When I run this through **avs-refreshToken-helper.js** I get:
`Redirect URI (allowed return URL)? http://localhost:9745/authresponse"
{ error_description: 'The request has an invalid parameter : code',
  error: 'invalid_request' }`

What am I doing wrong ? 

I'm totally new to Amazon & Alexa.

**Comment by OliverLundgren** [comment]
Use this as the Redirect URL: https://sakirtemel.github.io/MMM-alexa/
This is what i used, be sure to have it allowed in the security profile.

Then use the avs token helper as you did before

**Comment by TheStigh** [comment]
> Use this as the Redirect URL: https://sakirtemel.github.io/MMM-alexa/
> This is what i used, be sure to have it allowed in the security profile.
> 
> Then use the avs token helper as you did before

What security profile ?

**Comment by OliverLundgren** [comment]
> > Use this as the Redirect URL: https://sakirtemel.github.io/MMM-alexa/
> > This is what i used, be sure to have it allowed in the security profile.
> > Then use the avs token helper as you did before
> 
> What security profile ?
For your alexa product.

The same as you did with "Allowed return URLs : http://localhost:9745/authresponse"
But instead of localhost use  https://sakirtemel.github.io/MMM-alexa/

**Comment by TheStigh** [comment]
Still get:
`{ error_description: 'The request has an invalid parameter : code',
  error: 'invalid_request' }
`
Don't understand what I'm doing wrong...

**Comment by TheStigh** [comment]
Sorted out, did something wrong :) Closing topic.
