### ISSUE TITLE
Alexa doesn't start

### ISSUE THREAD

**Issue by AWSb24** [dolanmiu/MMM-awesome-alexa#162]
Hi, 

I successfully finished Alexa and Audio setup but Alexa doesn't appear but as soon as I activate Alexa in the config the 'Wetterwarnungen' moves from the right side to the middle of the screen. Alexa doesn't also react on an voice command.
![screenshot](https://user-images.githubusercontent.com/49698426/56247605-a3790b00-60a5-11e9-9078-37429ab57a55.png)

Thanks for your help

**Comment by SamerAl-khateeb** [comment]
Hello, Can you please help me with how you got it to work in the first place? I followed all the instructions in this [YouTube video](https://youtu.be/bWzTdv5HbVU?t=50)  to set up Amazon Developer account and set up an Alexa Device. I also went through all the steps in this [github rep](https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/docs/Installation.md)  and this [github wiki](https://github.com/dolanmiu/MMM-awesome-alexa/wiki/How-to-get-AVS-Token-2). I obtained all the codes needed (client id, secret, product id, and refresh token, etc). After I did all the steps, every time I add the config to my magic mirror configuration file the screen go black and nothing works! I tried with my credentials and without it and in both cases the result is the same. Also, I tried the config in both formats, i.e., 
{
    "module": "MMM-awesome-alexa",
    "position": "bottom_bar",
    "config": {
        "wakeWord": "Alexa",
        "clientId": "YOUR_CLIENT_ID",
        "clientSecret": "YOUR_CLIENT_SECRET",
        "deviceId": "YOUR_DEVICE_ID",
        "refreshToken": "YOUR_REFRESH_TOKEN",
        "lite": false,
        "isSpeechVisualizationEnabled": false
    }
}

and 
{
    module: "MMM-awesome-alexa",
    position: "bottom_bar",
    config: {
        wakeWord: "Alexa",
        clientId: "YOUR_CLIENT_ID",
        clientSecret: "YOUR_CLIENT_SECRET",
        deviceId: "YOUR_DEVICE_ID",
        refreshToken: "YOUR_REFRESH_TOKEN",
        lite: false,
        isSpeechVisualizationEnabled: false
    }
}

Can you help me figure out what I am doing wrong? this is so much appreciated.

**Comment by dolanmiu** [comment]
Added documentation here on why it breaks and how to fix:

https://awesome-alexa.js.org/#/installation?id=modifying-magicmirror-electron
