### ISSUE TITLE
Cannot Access the Authorization Code 

### ISSUE THREAD

**Issue by DopeEthiop** [dolanmiu/MMM-awesome-alexa#163]
I setup my developer profile and I installed the module onto my Pi. However after I run the dev token and input the information, the link leads me to an error site. I don't know what the problem might be and I've tried multiple "Return URL" on my developer page. Below is the terminal code with the partial link I'm told to click and the error site.
![2019-04-19-172933_1824x984_scrot](https://user-images.githubusercontent.com/49375625/56445137-b3713480-62c9-11e9-9b55-992c7258df9b.png)

**Comment by Soowarez** [comment]
Hello, sorry in advance for my english. (I am French)
Same problem for me not managed to solve it.
But did you manage to install the module? no error the golds of installing npm install?

**Comment by dolanmiu** [comment]
The `error site` is correct, check your address bar

**Comment by dolanmiu** [comment]
I have re-wrote the helper tool to be more user friendly and easier to use:

https://awesome-alexa.js.org/#/installation?id=configuration
