### ISSUE TITLE
config-helper

### ISSUE THREAD

**Issue by iateyoucooki** [dolanmiu/MMM-awesome-alexa#170]
I'm a little lost. I'm trying to run 
$ npm run config-helper
and I get: 
npm ERR! missing script: config-helper

Have I missed downloading something?

0|MagicMir |     at TLSSocket.Parser._cbReadable (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:53:12)
0|MagicMir |     at TLSSocket.emit (events.js:182:13)
0|MagicMir |     at emitReadable_ (_stream_readable.js:540:12)
0|MagicMir |     at process._tickCallback (internal/process/next_tick.js:63:19) type: 'no', textCode: 'ALERT', source: 'authentication' }
0|MagicMir | Email notifier error:  { Error: LOGIN failed.
0|MagicMir |     at Connection._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:1502:11)
0|MagicMir |     at Parser.<anonymous> (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Connection.js:194:10)
0|MagicMir |     at Parser.emit (events.js:182:13)
0|MagicMir |     at Parser._resTagged (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:175:10)
0|MagicMir |     at Parser._parse (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:139:16)
0|MagicMir |     at Parser._tryread (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:82:15)
0|MagicMir |     at TLSSocket.Parser._cbReadable (/home/pi/MagicMirror/modules/email/node_modules/imap/lib/Parser.js:53:12)
0|MagicMir |     at TLSSocket.emit (events.js:182:13)
0|MagicMir |     at emitReadable_ (_stream_readable.js:540:12)
0|MagicMir |     at process._tickCallback (internal/process/next_tick.js:63:19) type: 'no', textCode: undefined, source: 'authentication' }

**Comment by dolanmiu** [comment]
which directory are you running that command from?

It has to be from the MMM-awesome-alexa directory
