### ISSUE TITLE
Stucked at Listening

### ISSUE THREAD

**Issue by jacktrack** [dolanmiu/MMM-awesome-alexa#172]
Hello, im using Pi3 with latest Rasbian Desktop, installed everything correctly from awesome-alexa guide, no errors. Mic/Sound works but everytime i say the wake word, thte circle appears and nothing happens. In dev console logs - listening payload object object, there are no files in temp folder. 
Is it network related ?

**Comment by dolanmiu** [comment]
can you run `npm start dev` and let me know if there are any errors in the console?

If there are no errors

is your room quiet? maybe its still recording?

**Comment by petarstoikov** [comment]
There are no errors - the last row is:
MMM-awesome-alexa received a notification: listening - Payload: [object Object] MMM-awesome-alexa.js:1

**Comment by jacktrack** [comment]
There are no errors. The last row says:
MMM-awesome-alexa reeceived a notification: listening - Payload [object Object] in mmm-awesome-alexa.js:1

Edit: Hmm okay, i tried another microphone and it works. Thank you.

**Comment by dolanmiu** [comment]
Glad you got it working
