### ISSUE TITLE
./auth_code sh syntax errors?

### ISSUE THREAD

**Issue by JavierTSalas** [dolanmiu/MMM-awesome-alexa#18]
Hello I'm trying to setup your module and got the warning that I needed to refresh my token. Went to run the script and now I'm getting errors. This is what I'm using 
`CLIENT_ID="omitted"
DEVICE_TYPE_ID="test_device"
DEVICE_SERIAL_NUMBER=123
REDIRECT_URI="https://localhost:9745/authresponse"
RESPONSE_TYPE="code"
SCOPE="alexa:all"
SCOPE_DATA="{\"alexa:all\": {\"productID\": \"$DEVICE_TYPE_ID\", \"productInstanceAttributes\": {\"deviceSerialNumber\": \"${DEVICE_SERIAL_NUMBER}\"}}}"

function urlencode() {
  perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"'
}

AUTH_URL="https://www.amazon.com/ap/oa?client_id=${CLIENT_ID}&scope=$(echo $SCOPE | urlencode)&scope_data=$(echo $SCOPE_DATA | urlencode)&response_type=${RESPONSE_TYPE}&redirect_uri=$(echo $REDIRECT_URI | urlencode)"

open ${AUTH_URL}`

> 
# If using Linux, use this command:
# xdg-open ${AUTH_URL}
>  I've also tried this as per the [old guide](https://miguelmota.com/blog/alexa-voice-service-authentication/)

errors: $ ./auth_code.sh 
./auth_code.sh: line 8: $'\r': command not found
./auth_code.sh: line 9: syntax error near unexpected token `$'{\r''
'/auth_code.sh: line 9: `function urlencode() {

on raspberri pi 3 running latest magic mirror version

**Comment by JavierTSalas** [comment]
As per https://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory 
The command  
`sed -i -e 's/\r$//' scriptname.sh t`

Fixed my issue. This happens when you write the script on a windows machine then send then run the script on your raspberri pi

**Comment by dolanmiu** [comment]
Nice :)

**Comment by JavierTSalas** [comment]
I'm having trouble getting a refresh token. I'm able to get to the Amazon Sign in page and it's correctly showing my project name but I can't sign in (I keep getting an error page). Any advice?

**Comment by dolanmiu** [comment]
I'm sorry, that part is out of my domain actually, perhaps try the original article which I based mine off:

https://miguelmota.com/blog/alexa-voice-service-authentication/
