### ISSUE TITLE
option to change language?

### ISSUE THREAD

**Issue by thetobyde** [dolanmiu/MMM-awesome-alexa#207]
Is there an option to change the language to German?

Thx Toby :)

**Comment by Jan-2005** [comment]
Wenn sie deutsch Sprechen erkennt Alexa das

**Comment by Opus26** [comment]
@thetobyde, @Jan-2005 Alexa can't recognize my voice in French. Have you find a way to change de language? I don't see anything in config or documentation.. and I'm not sure how I could do that. Maybe someone have an idea? (my skills in prog are very limited but I'm slowly getting better so I could try something more complicated if necessary :)
