### ISSUE TITLE
rec t.wav fail after reboot

### ISSUE THREAD

**Issue by AirBurn1** [dolanmiu/MMM-awesome-alexa#26]
I hope this is something simple but my commands do not seem to save after a reboot. Here are my steps

1) rec t.wav  (this gives me the error: rec FAIL formats: can't open input `default': snd_pcm_open error: No such file or directory)
2) I did arecord -l  (got address 1,0)
3) export AUDIODEV=hw:1,0
4) export AUDIODRIVER=alsa
5) rec t.wav (works and can see the bars go up and down with my voice)
6) sudo reboot
7) rec t.wav  (same error as step 1)

Any idea wha'is going on?

Setup:
rpi 3 running jessie
node v6.11.4
npm 3.10.10
nodejs v5.12.0

**Comment by dolanmiu** [comment]
Yeah, I have this same issue

Everytime I reboot, I have to run those commands again

Perhaps a script which automatically runs on start-up would fix this problem

**Comment by dolanmiu** [comment]
Either way, this is not an issue with `MMM-awesome-alexa`, so I am closing!
