### ISSUE TITLE
The guides are wrong.....

### ISSUE THREAD

**Issue by cowboysdude** [dolanmiu/MMM-awesome-alexa#28]
Following this for manual creation:

https://miguelmota.com/blog/alexa-voice-service-authentication/

Does not take you anywhere near the pages as described on the webpage.... perhaps there's a more clear explanation for this?
Using your page results in errors -> https://magic-mirror-avs.github.io/Alexa-Web-Helper/

SO is there a new updated guide to install this?  

Thank you

**Comment by dolanmiu** [comment]
Are you sure?

I did this literally just now, created a new Alexa voice service called Nov2017, and got a perfect response back:

![screen shot 2017-11-09 at 16 40 09](https://user-images.githubusercontent.com/2917613/32617360-b8a2b47a-c56c-11e7-9144-289e12299ca7.png)

**Comment by cowboysdude** [comment]
I'd really like to get this going .... so what I'll do is retry it.  A huge part of the confusion by some is that when you try to follow the guide to create on the Alexa site itself it's confusing and it looks nothing like the guide that is referred to.

**Comment by dolanmiu** [comment]
Yes, it seems Amazon has updated the interface so it looks totally different now

But I think it's easier to use

**Comment by cowboysdude** [comment]
No offense here but I'm just not getting something...... I just cannot get past the last step....

Client ID ---  Where does this all come from?
Client Secret  
Device Id

I literally have read everything I can find and cannot figure out how to get this info.... I have had an Amazon account since they started and I'm drawing a complete blank here.....

**Comment by cowboysdude** [comment]
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.

Honestly I'm not sure how much frustrating this can get..........

I put the info in the site and hit enter and get that.........

**Comment by cowboysdude** [comment]
This is what I get back when trying to get the Auth code..... suggestions??


We're sorry!An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
--

**Comment by cowboysdude** [comment]
OK working!!!  We can close this issue.....due to my ignorance.

**Comment by cowboysdude** [comment]
If anyone needs the sh files for the codes please let me know.....I have them working.   The errors are caused by something very simple...copying it directly and just using it..... IF you do that make sure you go through all the lines and change your double quotes.  THEY DO NOT COPY correctly and this will give you errors.......

**Comment by dolanmiu** [comment]
https://github.com/dolanmiu/MMM-awesome-alexa/pull/30

Adding sh files made by @cowboysdude
