### ISSUE TITLE
Can I run custom code with Alexa using this module?

### ISSUE THREAD

**Issue by henrikra** [dolanmiu/MMM-awesome-alexa#32]
I have a question: Can I run custom code with Alexa using this module? :)

**Comment by dolanmiu** [comment]
What do you mean by custom code?

**Comment by henrikra** [comment]
For example I would like to do http request to certain endpoint when I say certain command to Alexa :D

**Comment by dolanmiu** [comment]
I believe what you asked for is out of scope of this module, sorry!

You can try look at `IFTTT` or something similar

`MMM-awesome-alexa` literally only allows you to use AVS

**Comment by dolanmiu** [comment]
Closing because its out of scope
