### ISSUE TITLE
ALSA error

### ISSUE THREAD

**Issue by henrikra** [dolanmiu/MMM-awesome-alexa#35]
When looking at my logs with `pm2 logs MagicMirror` I can see lot of this kind of errors:
`0|MagicMir | ALSA lib pcm.c:8389:(snd_pcm_set_params) Channels count (1) not available for PLAYBACK: Invalid argument`

I am using usb sound card (Blackstorm Spectrum 5.1) on my raspberry pi and it is working fine. Alexa can hear me and I can hear her. But that log is pretty alarming 🤔

**Comment by dolanmiu** [comment]
Could it be related to this:

https://forum.voidlinux.eu/t/solved-alsa-channels-count-not-available/674

**Comment by henrikra** [comment]
I have already set
```
pcm.!default {
    type hw
    card 1
}

ctl.!default {
    type hw
    card 1
}
```

Because I have that usb sound card which is `card 1`and it works. But the mirror is outputting that error. Do you know where I can find speaker settings that your module is using?

**Comment by dolanmiu** [comment]
I have no idea im afraid, I have not touched any speaker settings!

**Comment by henrikra** [comment]
So how your mic is connected to raspberry pi?

**Comment by dolanmiu** [comment]
I've got this plug and play mic from here:

https://www.amazon.co.uk/Demarkt-Microphone-Makio-Laptop-Desktop/dp/B01CQKCTSM/ref=sr_1_1?ie=UTF8&qid=1513080229&sr=8-1&keywords=raspberry+pi+mic

And then followed this:

https://www.raspberrypi.org/forums/viewtopic.php?t=13088&p=332703

**Comment by henrikra** [comment]
I am pretty sure this https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/src/main/alexa-voice-service/audio-service.ts#L25 or this https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/src/main/alexa-voice-service/audio-service.ts#L36 is causing the issue 🤔

**Comment by dolanmiu** [comment]
From what I recall, that is the format Amazon accepts, this is why its there, omitting it may create dire consequences

Feel free to experiment though

**Comment by E3V3A** [comment]
@henrikra What is the output of these?
```bash
cat /proc/asound/modules
cat /proc/asound/cards
amixer
```

I think the problem is that THAT config still doesn't set the device plug default correctly.

Try this:
```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}

ctl.!default {
        type hw
        card 1
}
```
and restart alsa server with: `sudo /etc/init.d/alsa-utils restart`.

**Comment by henrikra** [comment]
Wow did not notice that this is still open. I fixed this long time ago :D Thanks for the help
