### ISSUE TITLE
Crash without internet

### ISSUE THREAD

**Issue by henrikra** [dolanmiu/MMM-awesome-alexa#40]
If internet is not available for a second as example and you make request with this module to alexa the module crashes. After this you can't ask anything from Alexa anymore. Here is the log
```
{ Error: getaddrinfo ENOTFOUND access-alexa-na.amazon.com access-alexa-na.amazon.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'access-alexa-na.amazon.com',
  host: 'access-alexa-na.amazon.com',
  port: 443 }
```

To reproduce:
1. start magic mirror
2. turn off wifi
3. ask something from alexa
4. See the same error as above

**Comment by dolanmiu** [comment]
Yeah, perhaps there should be error handling when there is no internet lol :joy:

**Comment by henrikra** [comment]
Yes I have added handling in #38 💪
