### ISSUE TITLE
Problem with the redirect in the bash script

### ISSUE THREAD

**Issue by peterrobie** [dolanmiu/MMM-awesome-alexa#5]
```
CLIENT_ID="amzn1.application-oa2-client.***"
DEVICE_TYPE_ID="test_device"
DEVICE_SERIAL_NUMBER=123
REDIRECT_URI="https://localhost:9745/authresponse"
RESPONSE_TYPE="code"
SCOPE="alexa:all"
SCOPE_DATA="{\"alexa:all\": {\"productID\": \"$DEVICE_TYPE_ID\", \"productInstanceAttributes\": {\"deviceSerialNumber\": \"${DEVICE_SERIAL_NUMBER}\"}}}"

function urlencode() {
  perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"'
}

AUTH_URL="https://www.amazon.com/ap/oa?client_id=${CLIENT_ID}&scope=$(echo $SCOPE | urlencode)&scope_data=$(echo $SCOPE_DATA | urlencode)&response_type=${RESPONSE_TYPE}&redirect_uri=$(echo $REDIRECT_URI | urlencode)"

open ${AUTH_URL}
```
The issue is that the URL encode does not match the Amazon redirect URI. Special characters are not allowed so this fails.

`redirect_uri=https%3A%2F%2Flocalhost%3A9745%2Fauthresponse`

Can't wait to get this up and going. So close, lol.

**Comment by peterrobie** [comment]
I actually resolved this issue. In the code instead of `redirect_uri=$(echo $REDIRECT_URI | urlencode)` I used the following: `redirect_uri=${REDIRECT_URI}`

This got me to the login screen for Amazon and then I got the error page.

```
We're sorry!
An error occurred when we tried to process your request. Rest assured, we're already working on the problem and expect to resolve it shortly.
```

There was no further information so I'm not sure why that wasn't working. Any Suggestions would be helpful. (Mac OS 10.12.3) My script is listed below.

```
CLIENT_ID="amzn1.application-oa2-client.24*************"
DEVICE_TYPE_ID="test_device"
DEVICE_SERIAL_NUMBER=123
REDIRECT_URI="https://localhost:9745/authresponse"
RESPONSE_TYPE="code"
SCOPE="alexa:all"
SCOPE_DATA="{\"alexa:all\": {\"productID\": \"$DEVICE_TYPE_ID\", \"productInstanceAttributes\": {\"deviceSerialNumber\": \"${DEVICE_SERIAL_NUMBER}\"}}}"

function urlencode() {
  perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"'
}

AUTH_URL="https://www.amazon.com/ap/oa?client_id=${CLIENT_ID}&scope=$(echo $SCOPE | urlencode)&scope_data=$(echo $SCOPE_DATA | urlencode)&response_type=${RESPONSE_TYPE}&redirect_uri=${REDIRECT_URI}"

open ${AUTH_URL}
```

**Comment by dolanmiu** [comment]
what is your redirect URI in your amazon developer page?

Is it: https://localhost:9745/authresponse?

**Comment by peterrobie** [comment]
Yes sir. Removing the urlencode did the trick and I get to the login now, but I'm getting an ambiguous error message from Amazon with no details at this point. Would you mind trying the above script and let me know if you're getting past the login?

**Comment by dolanmiu** [comment]
@peterrobie Very odd, I just tried the guide step by step and I got it working. I had to add REDIRECT_URI in the second part of the script though in `auth_code.sh`, so:

```sh
CLIENT_ID="amzn1.application-oa2-client.796ab90fc5844fdbb8efc1739..."
CLIENT_SECRET="1e3a306483c78510d4cdeb05e0a522f7ec3c1629ae1d53c325bfc..."
CODE="ANcUMLaDrkMtCwUSrIqc"
GRANT_TYPE="authorization_code"
REDIRECT_URI="https://localhost:9745/authresponse"

curl -X POST --data "grant_type=${GRANT_TYPE}&code=${CODE}&client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&redirect_uri=${REDIRECT_URI}" https://api.amazon.com/auth/o2/token
```

But otherwise, it works perfectly for me. Which region are you in? Maybe Amazon blocks your region. I am in the UK

**Comment by dolanmiu** [comment]
This is where the guide is referenced from:

https://miguelmota.com/blog/alexa-voice-service-authentication/

I found it missing some details, such as the firefox thing, so I made my own on the Wiki based on the above link

**Comment by peterrobie** [comment]
That's strange for sure. I'm in the U.S. so I doubt that we'd have any issues like that. A couple things that I noticed is my node and npm versions were slightly out of date. I removed the repo from modules and I'm going to go for a fresh install. Currently node is 7.10.0 and npm is 4.6.1.

The error that I was getting was "Invalid grant type" which was really odd and snowboy.node had an incorrect path. Instead of Electron-*/snowboy.node mine was something like nodeV-x86/snowboy.node

Hopefully upgrading the packages will make a difference.

**Comment by peterrobie** [comment]
Not sure if the API was having issues or not, but I got my refresh code. It's incredibly long though and just want to confirm that that's correct.

I can symlink the snowboy path and that "should" make it work.

**Comment by peterrobie** [comment]
Using the symlink I got the error.

Error: The module '/Users/peterrobie/Alexa/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v51-darwin-x64/snowboy.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

I did this and got the same error as it didn't update anything in the Release. Any suggestions would be helpful.

**Comment by dolanmiu** [comment]
Try using node 6.10.x, thats the one I am using on MacOS Sierra

snowboy does tend to be a problem. Lots of other people have complained too about it

delete `node_modules` and try again

**Comment by dolanmiu** [comment]
If you can, can you post an issue on the `snowboy` forum, they will help, they are usually good at replying:

https://github.com/Kitt-AI/snowboy/issues

**Comment by peterrobie** [comment]
Sounds good and I appreciate it. I'll remove the directory and try again. I'll also look up how to roll back to 6.10.x and see if that helps. Might update the docs too regarding that.

I did get the refresh code, but as I mentioned it was ~3 lines. Hopefully it's correct.

**Comment by dolanmiu** [comment]
> I did get the refresh code, but as I mentioned it was ~3 lines. Hopefully it's correct.

Yeah its 3 lines cos its super long so it wraps around 😂

**Comment by peterrobie** [comment]
lol, ok. Then I have the right response. Thanks for confirming.

**Comment by dolanmiu** [comment]
Use `n` to roll back, its the best thing ever:

https://github.com/tj/n

**Comment by peterrobie** [comment]
Ah, I'm using homebrew. So super easy.

brew search node
brew unlink node
brew install node@6

**Comment by dolanmiu** [comment]
good stuff!!!

>  I had to manually create a temp directory

So the temp folder needs to actually exist? I wouldve thought node would be smart enough

> ./node_modules/.bin/electron-rebuild --pre-gyp-fix
Which fixed the problem and could be added to the repo for others to quickly resolve in the readme.

Good idea, I will add this

**Comment by peterrobie** [comment]
Yes. The temp directory needs to be there. Could access the fs and add it if it's not there or just add it to the repo.

I think the big things that I had problems with were needing to rebuild electron and the node version. I may update to the newest node version and try it to see if it was just the electron-rebuild issue.

**Comment by dolanmiu** [comment]
Done, added temp folder, so it will always be there now, and also ammended the "electron-rebuild" command (it was alrteady there actually, so it does --pre-gyp-fix:

```bash
$ npm run electron-rebuild 
```

If you run that, it is an alias to:

```bash
$ electron-rebuild --pre-gyp-fix
```
(You dont need to explicitly state `./node_modules/.bin/`)

**Comment by peterrobie** [comment]
Sounds great! Thanks for working with me on this.

**Comment by dolanmiu** [comment]
No problem! my pleasure

The next step is getting it working on Raspberry Pi, I ordered a raspberry pi microphone off Amazon few days ago, should arrive soon, then this module will be **boss**

**Comment by peterrobie** [comment]
No joke! I like it, but I noticed there's some setup for Alexa that's
required like setting your location. Might be a good idea to add that too.
Working on setting up my calendar and such with it later tonight.

Looking at getting a Pi v3 in a couple weeks and setting up the smart
mirror with Alexa. I have a 32" TV that's not really doing anything so I
could go with that or a lighter and smaller monitor. Should be a lot of fun!

**Comment by dolanmiu** [comment]
Really? Where do you need to set your location? If you tell me, I will update that article

Yes, the Pi is amazing, I have 3 of them, one automating my entire fish tank. another automating the chicken coop, and another for MagicMirror, its great!

**Comment by peterrobie** [comment]
You mind if I get your email? That way we can chat more and take this off
github.

**Comment by dolanmiu** [comment]
dolan_miu@hotmail.com


But I am a fan of gitter.im:
https://gitter.im/awesome-alexa/Lobby

way quicker, we can do private chats too

[https://avatars-05.gitter.im/group/iv/1/5907c23fd73408ce4f5c44c5]<https://gitter.im/awesome-alexa/Lobby>

awesome-alexa/Lobby - Gitter<https://gitter.im/awesome-alexa/Lobby>
gitter.im
Where communities thrive Free for communities Join over 800K+ people Join over 90K+ communities Create your own community Explore more communities





________________________________

**Comment by henrikra** [comment]
I guess this was resolved so can this be closed? :D

**Comment by dolanmiu** [comment]
Closing

Thanks
