### ISSUE TITLE
Raspberry overheating with Visualizer

### ISSUE THREAD

**Issue by henrikra** [dolanmiu/MMM-awesome-alexa#53]
My raspberry is showing overheating icon when Alexa is not even speaking :O Also when she speaks the animation is very slow and does not look very natural :P

Here is picture:
![image](https://user-images.githubusercontent.com/12229968/34453389-70944a78-ed5c-11e7-8a25-67fe13d27bd2.png)

**Comment by dolanmiu** [comment]
hmm interesting

The slowness is probs due to raspberry pi not powerful enough to use canvas

maybe have an option in the config to enable/disable visualisation

Or not use canvas for visualising

**Comment by dolanmiu** [comment]
Made a PR which should fix the overheating

**Comment by dolanmiu** [comment]
And by the way, where did you get the glass for your mirror? The place I want to get it from will cost me around £200

**Comment by henrikra** [comment]
I did the mirror according to this tutorial: http://www.cyber-omelette.com/2016/12/smart-mirror.html
There is no special mirror. There is only normal glass and plastic cover on top of it ;)
