### ISSUE TITLE
Dependencies prefixed with @types should be in devDependencies

### ISSUE THREAD

**Issue by henrikra** [dolanmiu/MMM-awesome-alexa#59]
Only libraries should have types in dependencies. And since this is not library they should in devDependencies :)

**Comment by dolanmiu** [comment]
Yeah good point

I did this because of this:

https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

```
you NEED to place @types/* package with regular "dependencies". For other cases "devDependencies" are good enough.
```

But in our case, I suppose it doesn't need to be in `dependencies`

**Comment by dolanmiu** [comment]
Will make a PR

**Comment by henrikra** [comment]
Great! Should we also change README so that we install only `dependencies` with `npm install`? Only developers of this module need to install dev dependencies too

**Comment by dolanmiu** [comment]
https://github.com/Microsoft/types-publisher/issues/81

Good read here

**Comment by dolanmiu** [comment]
Good idea about README
