### ISSUE TITLE
Leaves process mid dialog

### ISSUE THREAD

**Issue by Reotch2** [dolanmiu/MMM-awesome-alexa#6]
Functions like Jeopardy or Ordering quit after a single action. 
Me: Alexa, let's play jeopardy.
Alexa: "THIS IS JEOPARDY"...
crickets......

**Comment by dolanmiu** [comment]
Ah yes, this is a known bug. 

I am aware of this. It also fails with commands which require confirmation, such as adding a calendar event:

Me: "Alexa, set an Event for tomorrow"
Alexa: "For what time?"
crickets.... 😄 

This is a limitation on MagicMirror believe it or not. Alexa uses HTTP/2 which allows for back and forth communication (which is what we need for this), node currently only supports HTTP/1.1

I will keep you updated!

**Comment by Reotch2** [comment]
Awesome. Thank you.
