### ISSUE TITLE
Is request really needed as dependency?

### ISSUE THREAD

**Issue by henrikra** [dolanmiu/MMM-awesome-alexa#73]
I was wondering if `request` is needed as dependency. I think it is in node's core. Or at least I was able to use it in my small project without any `package.json` 🤔

**Comment by henrikra** [comment]
Or maybe it works because MagicMirror already has it? https://github.com/MichMich/MagicMirror/blob/master/package.json#L65

**Comment by dolanmiu** [comment]
Yeah its used here :smile::

https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/src/main/alexa-voice-service/audio-service.ts

**Comment by dolanmiu** [comment]
> Or maybe it works because MagicMirror already has it? 

I don't know, perhaps! But I think we should keep it in. It is not guaranteed in future that MagicMirror will keep the `request` dependency

**Comment by henrikra** [comment]
Yeah I know that this module is using `request` but just wondering if it is really needed as double dependency when MagicMirror platform already has it :P I am very sure that people will quickly tell you in the issues if `request is undefined` :D

**Comment by henrikra** [comment]
@dolanmiu Have you tested this?

**Comment by dolanmiu** [comment]
I think we should keep request as a dependency, cos its uncertain what version of request MagicMirror is using (or will be using)

Imagine if MagicMirror updates their version of request, there is a chance it can break `MMM-awesome-alexa`! 😭

**Comment by henrikra** [comment]
Okay true. Lets close this 🌂
