### ISSUE TITLE
Module not responding

### ISSUE THREAD

**Issue by andrew16x** [dolanmiu/MMM-awesome-alexa#74]
Hello, and many thanks for creating this module. I am very keen to get started and experiment with it however I got a bit stuck and can't get it to work at all.

I have followed the setup steps provided in these two links:

https://github.com/dolanmiu/MMM-awesome-alexa
https://github.com/dolanmiu/MMM-awesome-alexa/wiki/How-to-get-AVS-Token

Like everyone one else, the most challenging bit was to obtain the refresh token, but with a bit of perseverance I have managed following the guide in the link above. I honestly though that the hard part was over and that all that I had left to do was to put everything together in the config.js file.

The problem I have is that, despite the fact that the mirror starts and loads all the modules correctly and I don't receive any errors - the Alexa module is unresponsive. Whenever I say the wake-word "Alexa", nothing happens.

Troubleshooting steps that I followed:

Tested the microphone - the official troubleshooting guide says to use the `rec t.wav` command however I get the following result when using it:  

`rec FAIL formats: can't open input  `default': snd_pcm_open error: No such file or directory`

I am able though to test the mic using this command

`$arecord -D plughw:1,0 -f cd test.wav`

and play back successfully using 

`$aplay test.wav`

I have tried to start the MagicMirror the traditional way of npm start as suggested on the forum but with no luck.

I have attached bellow the logs, for some reason I got different output when I ran it different times.

Output when running MagicMirror with npm start

> pi@raspberrypi:~/MagicMirror $ npm start
> 
> > magicmirror@2.2.2 start /home/pi/MagicMirror
> > sh run-start.sh
> 
> Starting MagicMirror: v2.2.2
> Loading config ...
> Loading module helpers ...
> No helper found for module: alert.
> Initializing new module helper ...
> Module helper loaded: updatenotification
> No helper found for module: clock.
> Initializing new module helper ...
> Module helper loaded: calendar
> No helper found for module: random_quotes.
> No helper found for module: currentweather.
> No helper found for module: weatherforecast.
> Initializing new module helper ...
> Module helper loaded: newsfeed
> Initializing new module helper ...
> Module helper loaded: MMM-MyCommute
> Initializing new module helper ...
> Module helper loaded: MMM-awesome-alexa
> All module helpers loaded.
> Starting server on port 8080 ... 
> Server started ...
> Connecting socket for: updatenotification
> Connecting socket for: calendar
> Starting node helper for: calendar
> Connecting socket for: newsfeed
> Starting module: newsfeed
> Connecting socket for: MMM-MyCommute
> ====================== Starting node_helper for module [MMM-MyCommute]
> Connecting socket for: MMM-awesome-alexa
> Sockets connected & modules started ...
> Launching application.
> Create new calendar fetcher for url: https://calendar.google.com/- Interval: 300000
> Create new news fetcher for url: http://feeds.bbci.co.uk/news/rss.xml?edition=uk - Interval: 300000
> Shutting down server...
> Stopping module helper: updatenotification
> Stopping module helper: calendar
> Stopping module helper: newsfeed
> Stopping module helper: MMM-MyCommute
> Stopping module helper: MMM-awesome-alexa
===================================================================
Log output 1:

> pi@raspberrypi:~/MagicMirror $ pm2 log MagicMirror
> [TAILING] Tailing last 15 lines for [MagicMirror] process (change the value with --lines option)
> /home/pi/.pm2/logs/MagicMirror-error-0.log last 15 lines:
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/dolanmiu/MMM-awesome-alexa.git/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/jclarke0000/MMM-MyCommute.git/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/KirAsh4/random_quotes/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/MichMich/MagicMirror.git/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/dolanmiu/MMM-awesome-alexa.git/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/jclarke0000/MMM-MyCommute.git/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/KirAsh4/random_quotes/': Could not resolve host: github.com
> 0|MagicMir | 
> 
> /home/pi/.pm2/logs/MagicMirror-out-0.log last 15 lines:
> 0|MagicMir | Connecting socket for: newsfeed
> 0|MagicMir | Starting module: newsfeed
> 0|MagicMir | Connecting socket for: MMM-MyCommute
> 0|MagicMir | ====================== Starting node_helper for module [MMM-MyCommute]
> 0|MagicMir | Connecting socket for: MMM-awesome-alexa
> 0|MagicMir | Sockets connected & modules started ...
> 0|MagicMir | Launching application.
> 0|MagicMir | Create new calendar fetcher for url: https://calendar.google.com/- Interval: 300000
> 0|MagicMir | Create new news fetcher for url: http://feeds.bbci.co.uk/news/rss.xml?edition=uk - Interval: 300000
> 0|MagicMir | Shutting down server...
> 0|MagicMir | Stopping module helper: updatenotification
> 0|MagicMir | Stopping module helper: calendar
> 0|MagicMir | Stopping module helper: newsfeed
> 0|MagicMir | Stopping module helper: MMM-MyCommute
> 0|MagicMir | Stopping module helper: MMM-awesome-alexa

===================================================================

Log output 2:

> pi@raspberrypi:~/MagicMirror $ pm2 log MagicMirror
> [TAILING] Tailing last 15 lines for [MagicMirror] process (change the value with --lines option)
> /home/pi/.pm2/logs/MagicMirror-error-0.log last 15 lines:
> 0|MagicMir | WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
> 0|MagicMir | WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
> 0|MagicMir | WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
> 0|MagicMir | WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
> 0|MagicMir | WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
> 0|MagicMir | (node:27787) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: getaddrinfo EAI_AGAIN api.amazon.com:443
> 0|MagicMir | (node:27787) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 0|MagicMir | fatal: unable to access 'https://github.com/MichMich/MagicMirror.git/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/dolanmiu/MMM-awesome-alexa.git/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/jclarke0000/MMM-MyCommute.git/': Could not resolve host: github.com
> 0|MagicMir | 
> 0|MagicMir | fatal: unable to access 'https://github.com/KirAsh4/random_quotes/': Could not resolve host: github.com
> 0|MagicMir | 
> 
> /home/pi/.pm2/logs/MagicMirror-out-0.log last 15 lines:
> 0|MagicMir | Connecting socket for: MMM-awesome-alexa
> 0|MagicMir | Sockets connected & modules started ...
> 0|MagicMir | Launching application.
> 0|MagicMir | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/andrei.v.danci%40gmail.com/private-b434c77e5b2246cf7ab50c3f34946419/basic.ics - Interval: 300000
> 0|MagicMir | Create new news fetcher for url: http://feeds.bbci.co.uk/news/rss.xml?edition=uk - Interval: 300000
> 0|MagicMir | Shutting down server...
> 0|MagicMir | Stopping module helper: updatenotification
> 0|MagicMir | Stopping module helper: calendar
> 0|MagicMir | Stopping module helper: newsfeed
> 0|MagicMir | Stopping module helper: MMM-MyCommute
> 0|MagicMir | Stopping module helper: MMM-awesome-alexa
> 0|MagicMir | 
> 0|MagicMir | > magicmirror@2.2.2 start /home/pi/MagicMirror
> 0|MagicMir | > sh run-start.sh
> 0|MagicMir | 

I would really appreciate your assistance in trying to get this resolved.

Many thanks and best regards,

Andy

**Comment by henrikra** [comment]
Are you using usb sound card?

**Comment by andrew16x** [comment]
Hi, 


No, I have a USB microphone ( Kinobo - Mini "AKIRO") connected directly to the raspberry pi.

**Comment by henrikra** [comment]
Have you setup those correctly? Can you record and play sounds with some other programs?

**Comment by andrew16x** [comment]
I've only tested the mic using this command
$arecord -D plughw:1,0 -f cd test.wav

and since I was able to play back I assumed it was installed correctly and have not tested via any other apps.

What setup steps would you suggest I should double check or apps I could use to confirm it is working?

**Comment by dolanmiu** [comment]
This module only works with the `rec` command currently.
`arecord` is not supported

This entire library is basically a fancy wrapper around `rec` 😂

**Comment by henrikra** [comment]
@dolanmiu But isn't recording handled by `node-record-lpcm16`?

**Comment by dolanmiu** [comment]
@henrikra yes, but that wraps `rec`

And I just found something cool, it turns out you can change the command used:

https://github.com/gillesdemey/node-record-lpcm16/blob/master/index.js#L20

**Comment by andrew16x** [comment]
Hi guys, I have changed from `rec` to `arecord` on #L20 in node-record-lpcm16/index.js 

To no avail... 

Any other ideas please?

I have attached a couple of screenshots from my alsamixer. 

By default, when I press F4, there is no capture device set, not sure if this would be the issue or not..?

![1](https://user-images.githubusercontent.com/35963444/35771476-574d779e-0925-11e8-9aa6-2f57295be681.JPG)
![2](https://user-images.githubusercontent.com/35963444/35771477-5764969a-0925-11e8-9c50-96d011c8e044.JPG)
![3](https://user-images.githubusercontent.com/35963444/35771479-577b83e6-0925-11e8-8b0f-92be84ce9bec.JPG)

**Comment by henrikra** [comment]
If I go to my alsamixer and press f4 I see this
![image](https://user-images.githubusercontent.com/12229968/35771551-5966b09c-0937-11e8-869f-99f3b7042b5c.png)

So I have capture device by default :P That can be one problem since it would make sense to have default recording device

Here is what I see when I press f3
![image](https://user-images.githubusercontent.com/12229968/35771564-841ba7c0-0937-11e8-9109-a7939c5e73f7.png)

**Comment by henrikra** [comment]
Also check this https://www.alsa-project.org/main/index.php/Asoundrc
I had to edit my ~/.asoundrc so my system uses my usb sound card by default I think you have to do something similar. Please read that link I hope it helps you.
Here is my `~/.asoundrc`:
```
pcm.!default {
        type hw
        card 1
}

ctl.!default {
        type hw
        card 1
}
```

**Comment by andrew16x** [comment]
@henrikra , when you mention "my usb sound card", do you actually have a USB sound card or is it your USB microphone that you refer to? 

Anyways, I have created asoundrc.conf in my /home/pi folder and inside it I now have:

pcm.!default {
	type hw
	card 1
}

ctl.!default {
	type hw           
	card 1
}

Again, this has made no difference, I still can't wake up Alexa and when I go into alsamixer, there still isn't any capture device present by default.

 I have opened Preferences/Audio Device Settings and this is what I'm seeying:

![audio1](https://user-images.githubusercontent.com/35963444/35777783-add48c66-09ab-11e8-9bda-0df693e0354e.JPG)

Have even tried the "Make Default" button but the change does not stick.

![audio2](https://user-images.githubusercontent.com/35963444/35777794-e4775b0e-09ab-11e8-9f92-0660bbe75221.JPG)

From the terminal when I type in `lsusb` command to check the usb connection, this is what I get:

![lsusb1](https://user-images.githubusercontent.com/35963444/35777805-1ee66e42-09ac-11e8-9e56-4d65299df411.JPG)

and then check  the microphone with arecord using `arecord -l` I get this:

![arecord-l](https://user-images.githubusercontent.com/35963444/35777812-4577272c-09ac-11e8-9380-de800329a41e.JPG)

Then when I test by using following command, it works fine:

`arecord -D plughw:1,0 -d 3 test.wav && aplay test.wav`

Where am I going wrong?

**Comment by henrikra** [comment]
Yeah I am using Blackstorm Spectrum 5.1 usb sound card. But yeah looks like your problem is that your system does not have default mic set. Remember to try to restart the system when you modify for example `asoundrc` etc. Also you can try to add logging to alexa module for example here https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/src/main/detector.ts#L27 if the mic can pick anything.

To me this does not look like it is alexa module problem and rather than default mic is not set :)

**Comment by andrew16x** [comment]
I've just realised that when typing `aplay -l` I don't see the USB microphone listed. Would have expected to see a card 1: USB device as I've seen on forums other people are getting.

![aplay-l](https://user-images.githubusercontent.com/35963444/36076251-8a9f9dca-0f51-11e8-9923-b006962fc2ab.JPG)

However when I do `lsusb` I get the following, the mic being the second one down listed (JMTech)

![lsusb](https://user-images.githubusercontent.com/35963444/36076267-be5f9e1c-0f51-11e8-9fa1-83026e72a1fc.JPG)

So probably the asoundrc.conf file I created won't work anyway because I don't have a card 1.
The file currently looks like this:

`pcm.!default {
	type hw
	card 1
}

ctl.!default {
	type hw           
	card 1
}`

Could it be that the type/brand of microphone I have is not compatible with `aplay -l`?

Any other ideas on how to install this properly so that it does get recognised?

**Comment by henrikra** [comment]
No idea from me. When I bought my USB sound card I can see it from `aplay -l` without any extra configuration. So I guess your problem is that you have to get your usb mic listed so ALSA knows about it

**Comment by andrew16x** [comment]
I'm starting to think that it's not a config issue but the actual hardware I'm using, and the fact that I don't have a USB sound card in which I then could plug a 3.5 jack mic (which could therefore be recognised as card 1 from aplay - l). 

Has anyone got the same setup as me and managed to get awesome alexa module working?
Raspberry pi 3 model B
USB microphone connected directly to pi
HDMI sound output through the TVs speakers 

Many thanks!

**Comment by andrew16x** [comment]
Hi all,

Quick update. I have made a slight change to my hardware configuration. Instead of the USB microphone I now have a USB sound card with a 3.5mm jack microphone. 

I can confirm that alsamixer now correctly displays the default playback device. 

Couple of things:

1. Having the sound card as default, I now lost the sound output - which I would prefer to use from HDMI source (that way it can play directly through TV speakers). Is there a way to adjust asoundrc.conf to use default mic from USB sound card and default audio from HDMI?

2. The module still isn't responding to the wake word, still no errors received when starting the module (either by pm2 or npm). Have run `pm2 logs` , see bellow output - is the section highlighted of any concern and the reason why this is not working?

![capture](https://user-images.githubusercontent.com/35963444/36342660-7cec76b0-13f9-11e8-8cb5-cc16032a9139.JPG)


Appreciate all your help.

**Comment by henrikra** [comment]
This looks better. Maybe redo your auth tokens etc?

**Comment by henrikra** [comment]
Hey guys please check the audio guide I did: https://github.com/dolanmiu/MMM-awesome-alexa/pull/78

Tell me if it helps you or if you want to add something :)

**Comment by E3V3A** [comment]
@andrew16x  If you want to list audio input (recording) devices you use `arecord -l`, `aplay -l` is only for output devices. What is your current ALSA config? 

What is your output of these?
```bash
cat /proc/asound/modules
cat /proc/asound/cards
amixer -c 1
```
Here is another too long description of [how to get basic USB sound](https://raspberrypi.stackexchange.com/questions/80072/how-can-i-use-an-external-usb-sound-card-and-set-it-as-default) going. You should go through it. I don't think your problem is too serious or you would not have any sound at all. But please do change your hardware configuration in the middle of the issue topic. Try to get the basic working first, then you can change stuff around.

**Comment by henrikra** [comment]
Do you have rights to write to that folder you are trying to save recording?

**Comment by andrew16x** [comment]
I assumed I did have the correct rights as the same command works when I have card 1 set as default in asoundrc for both playback and recording.
