### ISSUE TITLE
Make NodeJS script to replace shell scripts

### ISSUE THREAD

**Issue by henrikra** [dolanmiu/MMM-awesome-alexa#81]
Looks like lots of people have trouble running shell scripts so maybe we should make better script with node so it would be easier to use? Or do you have any other ideas @dolanmiu ?

**Comment by dolanmiu** [comment]
Yes, a JS script would probably be more robust

We should make this the unified perfect solution

**Comment by henrikra** [comment]
I am on it 🔥

**Comment by E3V3A** [comment]
Although a good idea from aesthtics, I would rather say that shell scripts would be more "robust" as they don't depend on any other modules apart the standard (*nix) tools. If anything at all is missing in node, then the scripts wont, run and the user will never get their info. But I see that the script depends on Perl... so perhaps it just doesn't matter.

**Comment by E3V3A** [comment]
Please see #57
