### ISSUE TITLE
snowboy Error during installation

### ISSUE THREAD

**Issue by dpnkrg** [dolanmiu/MMM-awesome-alexa#84]
Hi everyone,

when tying to install MMM-awesome-alexa module, i am facing this issue:

npm install --only=prod
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg== integrity checksum failed when using sha512: wanted sha512-L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg== but got sha1-NgSLv/TntH4TZkQxbJlmnqWukfE=. (2872 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> snowboy@1.2.0 preinstall /home/pi/Downloads/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
> npm install node-pre-gyp

npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-pre-gyp@0.6.39
added 113 packages in 17.17s

> snowboy@1.2.0 install /home/pi/Downloads/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v59-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@9.6.1 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/home/pi/Downloads/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'
  CXX(target) Release/obj.target/snowboy/swig/Node/snowboy.o
In file included from ../../nan/nan.h:192:0,
                 from ../swig/Node/snowboy.cc:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:73: warning: ‘v8::Maybe<bool> v8::Object::ForceSet(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated: Use CreateDataProperty / DefineOwnProperty [-Wdeprecated-declarations]
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
                                                                         ^
In file included from /home/pi/.node-gyp/9.6.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.6.1/include/node/node.h:63,
                 from ../../nan/nan.h:49,
                 from ../swig/Node/snowboy.cc:1:
/home/pi/.node-gyp/9.6.1/include/node/v8.h:3165:29: note: declared here
                 Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                             ^
/home/pi/.node-gyp/9.6.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/snowboy.node
  COPY Release/snowboy.node
  COPY /home/pi/Downloads/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/lib/node/binding/Release/node-v59-linux-arm/snowboy.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/Downloads/MagicMirror/modules/MMM-awesome-alexa/node_modules/snowboy/build'

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/pi/Downloads/MagicMirror/modules/MMM-awesome-alexa/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

added 546 packages in 111.256s

**Comment by henrikra** [comment]
What node version you are running?

**Comment by dpnkrg** [comment]
v9.6.1

**Comment by henrikra** [comment]
Hmm MagicMirror officially supports Node 6v so you may want to try with node 6.x

**Comment by dpnkrg** [comment]
okay, will install node 6.x version and update

**Comment by dpnkrg** [comment]
MMM-awesome-alexa module successfully installed with node 6.x
Thanks @henrikra for your support.

**Comment by henrikra** [comment]
No worries! @dolanmiu should we add to the README that this module works best on Node 6?

**Comment by dolanmiu** [comment]
Yeah we should add that in, its important info 

Before, the README had information regarding node `7.x.x` and node `8.x.x`

We should maybe add that back in?

**Comment by henrikra** [comment]
I would prefer whitelisting over blacklisting. I can do PR later today if you want :D

**Comment by dolanmiu** [comment]
Ok sure thing :D
