### ISSUE TITLE
incorrect info in AudioSetup.md

### ISSUE THREAD

**Issue by E3V3A** [dolanmiu/MMM-awesome-alexa#85]
Some of the info you provided int he AudioSetup.md file is incorrect. Specifically: 
```
in pmc the p stands for playback. So were configuring playback settings inside this block
all you need to know that we are setting default card to 1 for playback
this number has to match your desired card that we looked up previous. For my case it is 1
in ctl the c stands for capture. So were configuring capture settings inside this block
```

1. It is `pcm` and not "pmc", and it stand for `Pulse Code Modulation`, and has nothing to do with playback.
2. `ctl` stand for `Control` and has nothing to do with capture.

Otherwise its great help info. :+1:

**Comment by henrikra** [comment]
Great! Is it possible for you to make PR for this? Just go here: https://github.com/dolanmiu/MMM-awesome-alexa/blob/master/docs/AudioSetup.md and press the little pencil icon 
![image](https://user-images.githubusercontent.com/12229968/37488113-45daceda-289c-11e8-9a69-927735a64667.png)

**Comment by E3V3A** [comment]
Yeah, I was thinking to do it right away, but I didn't wanna impose myself on other peoples playgrounds, without an invitation! ;)

**Comment by E3V3A** [comment]
done
