### ISSUE TITLE
What are the other config options doing?

### ISSUE THREAD

**Issue by E3V3A** [dolanmiu/MMM-awesome-alexa#87]
What are these config options doing?
```
        "lite": false,
        "isSpeechVisualizationEnabled": false
```

**Comment by E3V3A** [comment]
Ok I think that:

* `"lite":true`  When true is disabling the showing of a spinner when Alexa is listening
* `"isSpeechVisualizationEnabled": true`  is showing something more dynamic while you are being recorded

**Comment by dolanmiu** [comment]
isSpeechVisualizer is for the visualisation when alexa is speaking

lite is used for computers with lower power as sometimes the animations may be slow

**Comment by E3V3A** [comment]
Yep, I was just to clarify this:

> When "isSpeechVisualizationEnabled": true is activated, will their be an visual effect on the MM even while not talking?

This shows a few moving bubbles, while Alexa is talking. 

The other option is disabling of showing a vertical line (when Alexa is listening) and a wider vertical cat pupil (when processing).

**Comment by dolanmiu** [comment]
> The other option is disabling of showing a vertical line (when Alexa is listening) and a wider vertical cat pupil (when processing).

I had something similar effect, but it was incredibly slow on raspberry pi. The one right now is just barable

![image](https://user-images.githubusercontent.com/2917613/37612675-c105441a-2b9d-11e8-901e-25c5bba5ffe5.png)
