### ISSUE TITLE
Randomly stops responding

### ISSUE THREAD

**Issue by E3V3A** [dolanmiu/MMM-awesome-alexa#88]
After asking Alexa a few questions, "she" randomly stops responding to any wake words. 
I have nothing in any of my logs, so I have no idea why it happens.

Could it be a refresh (token) issue? (It should last at least 3600 seconds.)

**Comment by E3V3A** [comment]
So nobody else have noticed this issue?

**Comment by dolanmiu** [comment]
Nothing in the terminal logs, nor the `npm start dev` chromium logs?

It should say which state it is currently in. Post it here

**Comment by flyingchipmunk** [comment]
I've noticed if I ask for something that responds with a non-voice answer it stops responding. i.e. playing music, or easter-egg with sound i.e. "beam me up scotty"

**Comment by dolanmiu** [comment]
Yes that is a known issue

This module does not support streaming or two-way conversations yet

**Comment by dv46** [comment]
Is there something you can do about it? It's ok that the module doesn't support streaming or two-way conversations yet, but it's annoying if it gets stuck and Alexa doesn't answer anymore.

**Comment by dolanmiu** [comment]
No longer stuck on busy state

Fixed, and it's due to a MagicMirror bug

Read more here: https://awesome-alexa.js.org/#/installation?id=modifying-magicmirror-electron
