### ISSUE TITLE
Device_ID

### ISSUE THREAD

**Issue by Jonathan214** [dolanmiu/MMM-awesome-alexa#90]
I am sorry this must be a really dumb Question but how can i get that Device ID?

**Comment by Albiorix2016** [comment]
It’s what ever you named the product when you were setting it up on amazon

**Comment by dolanmiu** [comment]
Not a dumb question at all! It is also called the "Product ID". Look at screenshot

![image](https://user-images.githubusercontent.com/2917613/37800672-8c2b9048-2e1b-11e8-965e-ea64bce776ad.png)
