### ISSUE TITLE
Allowed URL Return...

### ISSUE THREAD

**Issue by justjim1220** [dolanmiu/MMM-awesome-alexa#93]
Anyone know what the Return URL is supposed to be?

I've ran the avs-token-helper using a few different ones and keep getting this...

![screenshot 13](https://user-images.githubusercontent.com/27590633/37869603-432a8dd6-2f88-11e8-88b6-0f25bf780588.png)

this is after Amazon asks for me to login and allow.

OR, is there something else I may be doing wrong???

**Comment by justjim1220** [comment]
Here are all the Allowed Return URL's I have in my product...

![screenshot 15](https://user-images.githubusercontent.com/27590633/37869774-f7f9951a-2f8b-11e8-9b55-247fdda78cab.png)

**Comment by Albiorix2016** [comment]
@justjim1220 when you setup alexa in the dev options did you set it up as a device or something else? sometimes how its categorized can cause this error to pop up as well. I know the LAN ip's probably wont work but the localhost and the sakirtemel should. i used the sakitemel address with the new system and it worked for me.

**Comment by justjim1220** [comment]
I followed the installation instructions step by step, so yeah, I set it up as a device like it says to in the instructions...

**Comment by justjim1220** [comment]
@Albiorix2016 
ok, so I followed your advice and it seemed to work, I think...

Is the Refresh Token Supposed to be a gazillion characters long???

**Comment by justjim1220** [comment]
it also returned an Access Token, that is also a gazillion characters long. Do I need to put that in the code in my config.js?
Also, there is a Token Type: "bearer", and a expires in: "3600"

How is it supposed to work if it expires in 3.6 seconds? I can't even transfer it to my config.js file that fast!!!

Sorry about all the questions... Kind of a noob to all this!

Thanks in advance!

**Comment by Albiorix2016** [comment]
I put the refresh token in the config as it said to do in the readme I’m
not really sure about the type and limit tbh, I’m still trying to get mine
to respond correctly when I say Alexa lol

**Comment by justjim1220** [comment]
where is snowboy supposed to be installed?

I am now getting an error that the module snowboy can't be found...

I have tried to install it in several different places, but still getting the same error!

**Comment by Albiorix2016** [comment]
I thought snowboy got installed when you did the npm install in the
mmm-Awesome-Alexa dir I could be wrong though, but snowboy has a repository
on github might just search the site for it I’m not exactly sure of the
address

**Comment by justjim1220** [comment]
well, so did I, but that is the message I am getting...

**Comment by E3V3A** [comment]
The allowed return URLs are not supposed to be going to anything live. It's just for pleasing the Amazon servers so that you get a repsonse, that you need to:
1. follow with external browser.
2. when you reach the "return url" -- pages doesn't exists, then you look in the "new" URL field and copy the `code=...` part.

**Comment by justjim1220** [comment]
Issue finally working   Thanks to @Albiorix2016

**Comment by dolanmiu** [comment]
Yes, `snowboy` does not work on windows platforms, which is crucial for this module to work

Sorry!

**Comment by henrikra** [comment]
@dolanmiu can you add this to readme with big letters that this module does not run on windows?
