### ISSUE TITLE
Snowboy - need alternative for Windows...

### ISSUE THREAD

**Issue by justjim1220** [dolanmiu/MMM-awesome-alexa#94]
Is there an alternative for snowboy that will work on Windows???

**Comment by Albiorix2016** [comment]
Wish I had an answer to that. I’ve only been using this on a pi and Linux
laptop

**Comment by dolanmiu** [comment]
I don't think there is a windows version, and I do not know of an alternative:

https://github.com/Kitt-AI/snowboy/issues/322

**Comment by TheIronNinja** [comment]
I just found picovoice here https://github.com/Picovoice/Porcupine
Still haven't tried it but it should work on Windows
