### ISSUE TITLE
this may sound like a stupid question...

### ISSUE THREAD

**Issue by justjim1220** [dolanmiu/MMM-awesome-alexa#95]
I guess I'm having a brain fart day...

How do I update a package or a repository???

**Comment by dolanmiu** [comment]
To update, you edit the `package.json` to the version you want, then run `npm install`

But I am not sure why you would want to do this

**Comment by dolanmiu** [comment]
I am updating this as we speak

**Comment by dolanmiu** [comment]
Im going to close this!

**Comment by justjim1220** [comment]
K
