### ISSUE TITLE
Alexa response 

### ISSUE THREAD

**Issue by andrew16x** [dolanmiu/MMM-awesome-alexa#96]
Hello, 

Thanks with all your help received in issue #74, the audio configuration is finally OK and set exactly the way I wanted.

So without any other changes I went ahead and tested the module again. 

To my great surprise, the wake word works, the gray circle appears however no matter what I ask, the response I get back is: 

"Sorry, I'm not sure about that"

**Comment by andrew16x** [comment]
I have noticed that after I say the wake word it takes a good couple of seconds for the circle to appear, almost like there is a lag somewhere, then I get the response stated above.

Woukd anyone know why this behaviour occurs?

As always, your help and feedback is greatly appreciated.

**Comment by dolanmiu** [comment]
This behavoir occours because of the implementation of this module

It first records all of your voice, saves it to disk, then uploads it to amazon servers, and then downloads the Amazon response and then plays it back.

So yeah, it is long lol

I was in the process of creating a streaming version, but I couldn't get it working! So we have this for now

**Comment by dolanmiu** [comment]
You can check what the module is sending to amazon by checking the `temp` folder

If it has your voice with the question, then it is working correctly

**Comment by andrew16x** [comment]
I find that this is actually working correctly with a caveat - very long response times... 

Previously I would say the wake word, would wait for the gray circle to pop up to acknowledge that Alexa has been activated,  but by that time, and before me asking any questions I would get the response "sorry, I'm not sure about that" 

However if I say the wake word and straight after ask the question, I will eventually (sometimes can take up to 30 seconds or more)  get a proper response from Alexa. 

I just can't explain this delay at the moment, what's causing it to be so annoyingly slow.

Has anyone else got this issue?

You were mentioning in previous update that it has to save the voice to disk, and then finally download back the Amazon response. Those transactions, would it help if I changed to anothet memory card with faster read/write speeds?

**Comment by dolanmiu** [comment]
@andrew16x no, the disk isn't the bottle neck, it would be your upload/download speed

Another problem could be too much background noise. Is it very noisey in your area? The module may think there is more to record.

**Comment by andrew16x** [comment]
This issue can now be closed as finally  the module works as it should.

For the benefit of others that might come across this issue, I did three things of which weirdly the last one  I believe resolved the problem.

1. Cloned memory card and copied image onto a faster SD card 
2. Drilled a dedicated slot in the frame so that the microphone is facing outwards rather than being enclosed completely in the frame (this is regarding what @dolanmiu mentioned about avoiding too much background noise)
3. Have set 'isSpeechVisualizationEnabled' to 'false' in the config file. Only after doing so, I have actually noticed that Alexa was responding in a normal timed fashion. Not sure why this would have caused the delay..? And although is now set to false, I still get the gray feedback circles once alexa is Activated, so again, what is that parameter meant to be doing..?

Anyways, many thanks all for your help.

**Comment by henrikra** [comment]
@dolanmiu should we disable `isSpeechVisualizationEnabled` by default since it is so heavy? I am not using it either because it is too much for Raspberry

**Comment by dolanmiu** [comment]
@henrikra I love the animation you made though 😂

**Comment by dolanmiu** [comment]
Stale, closing
