### ISSUE TITLE
No sound while using it

### ISSUE THREAD

**Issue by manojjenago** [dolanmiu/MMM-awesome-alexa#97]
Hi ,

I have successfully configured and invoked through Magic mirror module. However when I run a command , I see a circle comes and after sometime it feds away. I can not hear anything. 
I am using 3.5 mm speaker here. Is is only working with USB speakers.  I can play sound and issue commands normally through Microphone (USB) and speaker. 
This is what I see..

pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDM
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $

Please suggest.
Thanks,
MJ

**Comment by iqballk** [comment]
I also have the same problem. when i call "alexa", I see a circle comes and remain. I can not hear anything. iam using seeedstudio 2-mics hat for mic and audio out. pulseaudio not installed. 

omxplayer test.mp3 -o alsa command works and sound ok.

please help.

**Comment by henrikra** [comment]
People you are not telling nothing that would help :D
You have to always provide logs with `pm2 log MagicMirror` if you have issue. Also please copy paste also your `~/.asoundrc` file content.

**Comment by iqballk** [comment]
thanks henrikra..

found some access problems from magicmirror log and fixed. now awesome alexa working.. regards..

**Comment by henrikra** [comment]
Share your solution here since it can help others :)

**Comment by justjim1220** [comment]
Yes, @iqbalk, PLEASE share your solution!!!!!

**Comment by iqballk** [comment]
`pm2 log mm` shows an error `error: cannot open .git/FETCH_HEAD: Permission denied`. then i checked FETCH_HEAD folder permission with,
`ls -l /usr/local/Library/Taps/linode/cli/.git/FETCH_HEAD`
and
`ls -l /usr/local/.git/FETCH_HEAD`

both folders not exist in their locations according to those commands. so i create them. check `pm2 log mm` again. now all works ok.

**Comment by onkararj** [comment]
pm2 log MagicMirror
[PM2] Spawning PM2 daemon with pm2_home=/home/pi/.pm2
[PM2] PM2 Successfully daemonized
[TAILING] Tailing last 15 lines for [MagicMirror] process (change the value with --lines option)
[PM2][ERROR] No file to stream for app [MagicMirror], exiting.

**Comment by dolanmiu** [comment]
Stale thread, closing

Sound issues aren't part of this module, so it is hard to support

If there are files in the `/temp` folder, then it means this module is working
